<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" rel="icon" />
<title><?echo $this->meta_title;?></title>
<base href="<?PHP echo $this->url_to_templates;?>" />
<meta name="description" content="<?echo $this->meta_description;?>" />
<meta name="keywords" content="<?echo $this->meta_keywords;?>">
<!--Js code start-->
<script src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/SpryAccordion.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jquery.js"></script>


<!--select design code-->
<script type="text/javascript" src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/list-top-sele.js"> </script>
<!--select design code-->

<!--add to cart js code start-->
<script type="text/javascript" src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/common.js"> </script>
<!--add to cart js code End-->

<!--popup start  -->
<script type="text/javascript" src="javascript/jquery/colorbox/jquery.colorbox.js"></script>

<!--popup end  -->

<!--Tab Controls Styles & JS files -->
<script type="text/javascript">
var HTTP_SERVER= '<?echo $this->url_to_site;?>';
</script>
<script type="text/javascript" src="javascript/common.js"></script>
<!--end common js  -->

<!--Js code End-->

<!--stylesheet code staret-->
<!-- <link href="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/load.css" rel="stylesheet" type="text/css" />-->
 <link href="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/load.css" rel="stylesheet" type="text/css" />
 
<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/ie7.css" />
<![endif]-->
<!--[if lt IE 7]>
<link rel="stylesheet" type="text/css" href="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/ie6.css" />
<script type="text/javascript" src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/DD_belatedPNG_0.0.8a-min.js"></script>
<script type="text/javascript">
DD_belatedPNG.fix('#logo img');
</script>
<![endif]-->

<link rel="stylesheet" type="text/css" href="javascript/jquery/colorbox/colorbox.css" />



<!--stylesheet code End-->


<!--tabs code End-->
<script type="text/javascript" src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/tabs.js"></script>

<!--tabs code End-->
</head>

<body>

<div class="main-wraper"> <!-- main-wraper start-->

<div class="main-top-menu">
<!-- main-top-menu start-->
<div id="container">
<!-- container start-->
<div class="top-menu">
<!-- top menu start-->
<div id="welcome">
<a href="<?php echo HTTP_SERVER;?>" class="home"><span><img src="<?php echo SITE_DEFAULT_TEMPLATE;?>/includes/images/home_icon.gif" alt="" border="0"/></span></a>
  <?php if (!$this->logged) { ?>
    <?php echo $this->text_welcome_header; ?>
    <?php } else { ?>
    <?php echo $this->text_logged_header; ?>
    <?php } ?>


</ul>
</div>
<div class="links">
  <ul>
   <li><a href="<?php echo $this->link_account;?>"><span><?php echo $this->trans->_('text_account_common_header');?></span></a></li>
		 <li><a href="<?php echo HTTP_SERVER."account/wishlist"?>" id="wishlist_total" ><span><?php echo $this->wishlistTotal;?></span></a></li>
                <li><a href="<?php echo $this->link_account_order_history?>"><span><?php echo $this->trans->_('text_order_common_footer');?></span></a></li>
                <li><a href="<?php echo HTTP_SERVER."checkout/cart"?>"><span><?php echo $this->trans->_('heading_title_checkout_checkout');?></span></a></li>
  </ul>
</div>
<!-- top menu End-->
</div>
<!-- container End-->
</div>
<!-- main-top-menu End-->
</div>


<div class="main-header">
  <!-- main-header start-->
  <div id="container">
    <!-- container start-->

<div id="header"><!-- header start-->

      <div id="logo"> <a href="<?php echo HTTP_SERVER.'index/index';?>"><img src="<?echo PATH_TO_UPLOADS."image/".STORE_LOGO?>"  alt=" bebuyer9 logo" /></a></div>
	  
<!--language start--> 
   <?php if(count($_SESSION['Lang']['languages'])>1){?>
      <div id="language">  
       	<form name="frmLang" id="frmLang" method="post" action="">

	<select name="lang" id="lang" class="language"  onchange="document.getElementById('frmLang').submit();">
               <?php
		foreach($_SESSION['Lang']['languages'] as $l)
	       {
		 //$sel=$this->lang->_languageCode==$l[code]?'selected':'';
		 $sel=$_SESSION['Lang']['language_code']==$l[code]?'selected':'';
		 echo "<option value='".$l[code]."' ".$sel." >".$l[name]."</option>";
	       }?>
            </select>

	    </form>
</div>
<?}?>
<!--language End--> 



     <!--currency start-->
     <?php

	if(count($this->curr->currencies)>1){
	?>
      <div id="currency"> 
      <form name="frmCurr" id="frmCurr"  method="post" action="">
   
	        <select name="curr" id="curr" class="language" onclick="document.getElementById('frmCurr').submit();">
               <?php
		foreach($this->curr->currencies as $k=>$v)
	       {
	       	 //$sel=$this->curr->_currency==$k?'selected':'';
		 $sel=$_SESSION['Curr']['currency']==$k?'selected':'';
		 echo "<option value='".$k."' ".$sel." >".$k."</option>";
	       }?>
            </select>
			
	    </form> 
      </div>
      <?}?>
      <!--currency End-->

   <div id="cart"><!--add to cart start-->
    <div class="heading">
      <h4><?php echo $this->trans->_('text_cart_common_header');?></h4>
      <a><span id="cart_total"><?php echo $this->text_items; ?></span></a></div>
    <div class="content">
	
	</div>
   <!--add to cart End-->  </div>

  
  
  <div id="contact">
  <div class="heading">
  <a><span id="cart_total">Support@rcartrs.com<br />
Callus: 800 900 027</span></a>  </div>
  </div>
  
      <div id="offers">
      
      <div class="header">
      <div class="offer-title"><span>Top Announcements</span></div>
      <p>20% OFF on iPhone. <a href="">Click Here</a></p>
      </div>
      </div>
      
  <!-- header End-->   </div>
  <!-- container End--> </div>
<!-- main-header End--></div>

<div id="main-menu"><!-- main-menu start-->

<div id="container"><!-- container start-->
<?php
	if ($this->menucategories) { ?>
<div id="menu">
<ul>
 <?php foreach ($this->menucategories as $category) {
       if($category['name']!="")
       {
       ?>
	    <li>
	  <a href="<?php echo $category['href']; ?>" class="first" ><span><?php echo $category['name']; ?></span></a>
	    <?php if ($category['children']) { ?>
<div class="style">
<?php for ($i = 0; $i < count($category['children']);) { ?>
<ul>
<?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
          <?php for (; $i < $j; $i++) { ?>
          <?php if (isset($category['children'][$i])) { ?>
 <li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
          <?php }} ?>

        </ul><?php } ?>

      </div><?php } ?>
	  
	   <?php } }?>
        </li>
		
			<?php }
	if($this->more=='1'){?>
		 <li>
        	<a href="#"><?echo $this->trans->_('text_more_common_header');?></a>
		 <div class="sub" style="opacity: 0; display: none; width: 150px;">
		 <?php foreach ($this->allCategories as $category) {if($category['top']!="1" && $category['name']!=""){
//foreach ($this->allCategories as $category) {if($category['top']!="1"){ ?>

                    <ul>
                        <li><h2> <a href="<?php echo $category['href']; ?>" class="first" ><?php echo $category['name']; ?></a></h2>
						 <?php if ($category['children']) { ?>
        <?php for ($i = 0; $i < count($category['children']);) { ?>
          <?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
          <?php for (; $i < $j; $i++) { ?>
          <?php if (isset($category['children'][$i])) { ?>
          <li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
          <?php } ?>
          <?php } ?>

        <?php } ?>

      <?php } ?>
                    </ul>

       <?}}?>
      </div>
	  
        </li><?}?>
<form name="frmsearch" id="frmsearch" method="post">
	  <li id="search"><div class="search-button" onclick="fnsearch();"></div>
                </li>
					   
			        <li id="search"  >
<span> 
	    <select id="dd" name="dd" class="search-product" >
              <option value="0"><?php echo $this->trans->_('text_all_categories_common_header');?></option>
              <?php

	      foreach ($this->catDropDown as $category_dropdown) { ?>
              <?php if ($category_dropdown['name'] == $category_id) { ?>
              <option value="<?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?>" selected="selected"><?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?></option>
              <?php } else { ?>
              <option value="<?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?>"><?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?></option>
              <?php } ?>
              <?php } ?>
            </select></span> 
                </li>
			   
<li id="search">
       
		<input name="q" id="q" type="text" value="<?php echo $this->trans->_('text_search_common_header');?>" class="search"   onfocus="if(this.value=='<?php echo $this->trans->_('text_search_common_header');?>')value=''"/>

               </li>
  </form>
</ul>

</div>

<!-- container End--> </div>
<!-- main-menu End--></div>


