<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>
                    	<?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?>                  </p>
                 <!--readcrumb End--></div>
				 
                         <!-- <div class="page-title"><h1><? echo $this->trans->_('heading_title_information_contact');?></h1></div>-->
						    <div class="page-title "><h1><span><?php echo $this->trans->_('text_location_information_contact'); ?></span></h1></div>
						 
				<div class="box">
			
	<form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="contactform">

    <div class="box-content-main">
    <div class="box-content">
	   <div class="contact-info-left">
      <div class="content"><div class="left"><b><?php echo $this->trans->_('text_address_information_contact'); ?></b><br />
        <?php echo $this->data[store]; ?><br />
        <?php echo $this->data[address]; ?></div>
   <div class="right">
        <?php if ($this->data[telephone]) { ?>
        <b><?php echo $this->trans->_('text_telephone_information_contact'); ?></b><br /><?php echo $this->data[telephone];?>
        <br />
        <?php } ?>
        <?php if ($fax) { ?>
        <b><?php echo $this->trans->_('text_fax_information_contact'); ?></b><br />
        <?php echo $this->data[fax]; ?>
        <?php } ?>
      </div>
    </div>
	</div>
	<div id="clear"></div>
    </div>
 
    <div class="contact-info-right">
	<div class="contact-form">
  <div class="contact-name">  <b><?php echo $this->trans->_('entry_name_information_contact'); ?></b></div>
 <div class="contact-textbox"> <input type="text" name="name" value="<?php echo $this->data[name]; ?>" /></div>
    <div id="clear"></div>
	</div>
    <?php if ($this->data[error_name]) { ?>
    <span class="error"><?php echo $this->data[error_name]; ?></span>
    <?php } ?>
    	<div class="contact-form">
  <div class="contact-name">  <b><?php echo $this->trans->_('entry_email_information_contact'); ?></b></div>
 <div class="contact-textbox">   <input type="text" name="email" value="<?php echo $this->data[email]; ?>" /></div>
    <div id="clear"></div>
	</div>
    <?php if ($this->data[error_email]) { ?>
    <span class="error"><?php echo $this->data[error_email]; ?></span>
    <?php } ?>
    <div class="contact-form">
  <div class="contact-name"> <b><?php echo $this->trans->_('entry_enquiry_information_contact'); ?></b></div>
 <div class="contact-textbox">   <textarea name="enquiry" cols="140" rows="5" style="width: 99%;"><?php echo $this->data[enquiry]; ?></textarea></div>
    <div id="clear"></div>
	</div>
	
	    <div class="contact-form">
    <?php if ($this->data[error_enquiry]) { ?>
    <span class="error"><?php echo $this->data[error_enquiry]; ?></span>
    <?php } ?>
    
	<div class="contact-name"><b><?php echo $this->trans->_('entry_captcha_information_contact'); ?></b></div>
    <div class="contact-textbox"><input type="text" name="captcha" value="<?php echo $this->data[captcha]; ?>" />
    <br />
      <img src="<?php echo $this->url_to_site.'ajax/captcha';?>" alt="" />
    <?php if ($this->data[error_captcha]) { ?>
    <span class="error"><?php echo $this->data[error_captcha]; ?></span>
    <?php } ?></div>
	<div id="clear"></div>
	</div>
	
	<DIV class="contact-form">
    <div class="contact-name"></div>
	<div class="contact-textbox">
      <div class="right"><a onclick="$('#contactform').submit();" class="button_btn"><span><?php echo $this->trans->_('button_submit_information_contact'); ?></span></a></div>
    </div></div>
	
    </div>
  </form>
						</div>
						 </div>
						 </div>
		   
		    </div>



                <!--rightContainer -->
<?if(count($this->pos[bottom])>0){?>
<div class="container-top">
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?></div>
<?}
?>				</div>
            <!--innerContent --></div>
    	<!--contentArea -->
