<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>

                    	<?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?></p>                    <!--innerpageBar --></div>
                  
				   <div class="page-title">
<h1><? echo $this->trans->_('heading_title_information_sitemap');?></h1></div>
			
				<div class="box">
				 <div class="box-content-main">
				<div class="box-content">
		  <div class="sitemap-info">
    <div class="left">
      <ul>
        <?php foreach ($this->data[categories] as $category_1) { ?>
        <li><a href="<?php echo $category_1['href']; ?>"><?php echo $category_1['name']; ?></a>
          <?php if ($category_1['children']) { ?>
          <ul>
            <?php foreach ($category_1['children'] as $category_2) { ?>
            <li><a href="<?php echo $category_2['href']; ?>"><?php echo $category_2['name']; ?></a>
              <?php if ($category_2['children']) { ?>
              <ul>
                <?php foreach ($category_2['children'] as $category_3) { ?>
                <li><a href="<?php echo $category_3['href']; ?>"><?php echo $category_3['name']; ?></a></li>
                <?php } ?>
              </ul>
              <?php } ?>
            </li>
            <?php } ?>
          </ul>
          <?php } ?>
        </li>
        <?php } ?>
      </ul>
    </div>
    <div class="right">
      <ul>
        <li><a href="<?php echo $this->url_to_site."product/special"; ?>"><?php echo $this->trans->_('text_special_information_sitemap'); ?></a></li>
        <li><a href="<?php echo $this->url_to_site."account/account"; ?>"><?php echo $this->trans->_('text_account_information_sitemap'); ?></a>
          <ul>
            <li><a href="<?php echo $this->url_to_site."account/edit"; ?>"><?php echo $this->trans->_('text_edit_information_sitemap'); ?></a></li>
            <li><a href="<?php echo $this->url_to_site."account/password"; ?>"><?php echo $this->trans->_('text_password_information_sitemap'); ?></a></li>
            <li><a href="<?php echo $this->url_to_site."account/address"; ?>"><?php echo $this->trans->_('text_address_information_sitemap'); ?></a></li>
            <li><a href="<?php echo $this->url_to_site."account/order"; ?>"><?php echo $this->trans->_('text_history_information_sitemap'); ?></a></li>
            <li><a href="<?php echo $this->url_to_site."account/download"; ?>"><?php echo $this->trans->_('text_download_information_sitemap'); ?></a></li>
          </ul>
        </li>
        <li><a href="<?php echo $this->url_to_site."checkout/cart"; ?>"><?php echo $this->trans->_('text_cart_information_sitemap'); ?></a></li>
        <li><a href="<?php echo $this->url_to_site."checkout/checkout"; ?>"><?php echo $this->trans->_('text_checkout_information_sitemap'); ?></a></li>
        <li><a href="<?php echo $this->url_to_site."product/search"; ?>"><?php echo $this->trans->_('text_search_information_sitemap'); ?></a></li>
        <li><?php echo $this->trans->_('text_information_information_sitemap'); ?>
          <ul>
            <?php foreach ($this->data[informations] as $information) { ?>
            <li><a href="<?php echo $information['href']; ?>"><?php echo $information['title']; ?></a></li>
            <?php } ?>
            <li><a href="<?php echo $this->url_to_site."information/contact"; ?>"><?php echo $this->trans->_('text_contact_information_sitemap'); ?></a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div></div>
		 </div>
		 </div>
		 </div>
		    </div>



                <!--rightContainer -->
<?if(count($this->pos[bottom])>0){?>
<div class="container-top">
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?></div>
<?}
?>				</div>
            <!--innerContent --></div>
    	<!--contentArea -->
