<?php
/*echo "<pre>";
				print_r($this->data);
				echo "</pre>";*/
if ($this->data[products] || $this->data[vouchers]) {?>
<table class="cart">
  <?php foreach ($this->data[products] as $product) {

  ?>
  <tr>
    <td class="image"><?php if ($product['thumb']) { ?>
      <a href="<?php echo $product['href']; ?>"><img src="<?php echo HTTP_SERVER."timthumb.php?src=".$product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>" /></a>
      <?php } ?></td>
    <td class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a>
      <div>
        <?php foreach ($product['option'] as $option) { ?>
        - <small><?php echo $option['name']; ?> <?php echo $option['value']; ?></small><br />
        <?php } ?>
      </div></td>
    <td class="quantity">x&nbsp;<?php echo $product['quantity']; ?></td>
    <td class="total"><?php echo $product['total']; ?></td>
    <td class="remove"><img src="<?echo URL_TO_TEMPLATES.SITE_DEFAULT_TEMPLATE;?>/includes/images/close.png" alt="<?php echo $this->data[button_remove]; ?>" title="<?php echo $this->data[button_remove]; ?>" onclick="removeCart('<?php echo $product['key']; ?>');" /></td>
  </tr>
  <?php } ?>
  <?php foreach ($this->data[vouchers] as $voucher) { ?>
  <tr>
    <td class="image"></td>
    <td class="name"><?php echo $voucher['description']; ?></td>
    <td class="quantity">x&nbsp;1</td>
    <td class="total"><?php echo $voucher['amount']; ?></td>
    <td class="remove"><img src="<?echo URL_TO_TEMPLATES.SITE_DEFAULT_TEMPLATE;?>/includes/images/close.png" alt="<?php echo $this->data[button_remove]; ?>" title="<?php echo $this->data[button_remove]; ?>" onclick="removeVoucher('<?php echo $voucher['key']; ?>');" /></td>
  </tr>
  <?php } ?>
</table>
<table class="total">
  <?php foreach ($this->data[totals] as $total) { ?>
  <tr>
    <td align="right"><b><?php echo $_SESSION['OBJ']['tr']->_($total['title']); ?></b></td>
    <td align="right"><?php echo $total['text']; ?></td>
  </tr>
  <?php } ?>
</table>

<div class="checkout">
<div class="checkout-view"><a href="<?php echo HTTP_SERVER."checkout/cart"?>" class="button_btn"><span>View Cart</span></a>
<a href="<?php echo $this->data[checkout]; ?>" class="button_btn"><span><?php echo $this->data[button_checkout]; ?></span></a></div>
</div>
<?php } else { ?>
<div class="empty"><?php echo $this->data['text_empty']; ?></div>
<?php } ?>
