<script type="text/javascript"><!--
var selected;
function selectRowEffect(object, buttonSelect) {
//alert("in select row effect")
  if (!selected) {
    if (document.getElementById) {
      selected = document.getElementById('defaultSelected');
    } else {
      selected = document.all['defaultSelected'];
    }
  }

  if (selected) selected.className = 'moduleRow';
  object.className = 'moduleRowSelected';
  selected = object;

// one button is not an array
  if (document.checkout_address.shipping[0]) {
    document.checkout_address.shipping[buttonSelect].checked=true;
  } else {
    document.checkout_address.shipping.checked=true;
  }
}

function rowOverEffect(object) {
	//alert("in row over effect");
  if (object.className == 'moduleRow') object.className = 'moduleRowOver';
}

function rowOutEffect(object) {
	//alert("in row out effect");
  if (object.className == 'moduleRowOver') object.className = 'moduleRow';
}
//--></script>

<?
/*echo "<pre>";
print_r($this->data[quotes]);
echo "</pre>";
exit;*/
?>

 <div id="caption"><p><?php echo $_SESSION['OBJ']['tr']->_('text_checkout_shipping_method_checkout_checkout'); ?></p></div>
<div style="clear:both;"></div> 
<div id="chkOutContent">
  <form action="checkout_shipping.php" method="post" name="checkout_address">
  <input type="hidden" name="raction" id="raction" value="process">
	<div id="chkOutConient_block">

<?php
//echo "value of shipping modules ".tep_count_shipping_modules();
//if (tep_count_shipping_modules() > 0) {
if ($this->data['count_shipping_modules'] > 0) {
?>

 

<?php
    if (sizeof($this->data[quotes]) > 1 && sizeof($this->data[quotes][0]) > 1) {
?>

  <div class="contentText">
    <div class="title-main">
      <p><span><?php echo '<strong>' . $_SESSION['OBJ']['tr']->_('text_shipping_method_checkout_checkout') . '</strong>'; ?></span></p>
    
	<p><?php echo "choose shipping method"; ?></p>
	</div>
  </div>

<?php
    } elseif ($this->data[free_shipping] == false) {
?>

  <div class="contentText">
    <div class="title-main">
      <p><span><?php echo '<strong>' . $_SESSION['OBJ']['tr']->_('text_shipping_method_checkout_checkout') . '</strong>'; ?></span></p>
    
	<p><?php echo "choose shipping method"; ?></p>
	</div>
  </div>

<?php
    }
?>

  <div class="contentText">
    <table border="0" width="100%" cellspacing="0" border="1" cellpadding="2">

<?php
 
    if ($this->data[free_shipping] == true) {
?>

      <tr>
        <td><strong><?php echo "free shipping"; ?></strong>&nbsp;<?php echo $this->data[quotes][$i]['icon']; ?></td>
      </tr>
      <tr id="defaultSelected" class="moduleRowSelected" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, 0)">
        <td style="padding-left: 15px;"><?php echo sprintf(FREE_SHIPPING_DESCRIPTION, $currencies->format(MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER)) . tep_draw_hidden_field('shipping', 'free_free'); ?></td>
      </tr>

<?php
    } else {
      $radio_buttons = 0;

      for ($i=0, $n=sizeof($this->data[quotes]); $i<$n; $i++) {
?>

      <tr>
        <td width="40" align="left" style="padding-left:15px;"  class="dashBar"><strong><?php echo $this->data[quotes][$i]['module']; ?></strong>&nbsp;<?php if (isset($this->data[quotes][$i]['icon']) && tep_not_null($this->data[quotes][$i]['icon'])) { echo $this->data[quotes][$i]['icon']; } ?></td>
		<td colspan="2" class="dashBar" ></td>
      </tr>

<?php
        if (isset($this->data[quotes][$i]['error'])) {
?>

      <tr>
        <td colspan="3"><?php echo $this->data[quotes][$i]['error']; ?></td>
      </tr>

<?php
        } else {
          for ($j=0, $n2=sizeof($this->data[quotes][$i]['methods']); $j<$n2; $j++) {
			  //PRINT_R($_SESSION['shipping']);
// set the radio button to be checked if it is the method chosen
            $checked = (($this->data[quotes][$i]['id'] . '_' . $this->data[quotes][$i]['methods'][$j]['id'] == $_SESSION[shipping]['id']) ? true : false);
//echo "checked ".$checked;
            if ( ($checked == true) || ($n == 1 && $n2 == 1) ) {
              echo '      <tr id="defaultSelected" class="moduleRowSelected" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, ' . $radio_buttons . ')">' . "\n";
            } else {
              echo '      <tr class="moduleRow" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, ' . $radio_buttons . ')">' . "\n";
            }
?>

        <td width="35%" style="padding-left: 60px; text-align:left;"><strong><label for="<?php echo $this->data[quotes][$i]['id'] . '_' . $this->data[quotes][$i]['methods'][$j]['id']?>"><?php echo $this->data[quotes][$i]['methods'][$j]['title']; ?></label></strong></td>

<?php
            if ( ($n > 1) || ($n2 > 1) ) {

	//print_r($currencies);
	//echo $quotes[$i]['methods'][$j]['cost'];
	//echo tep_add_tax($quotes[$i]['methods'][$j]['cost'], (isset($quotes[$i]['tax']) ? $quotes[$i]['tax'] : 0));
?>

        <td width="35%" style="padding-left: 15px; "><strong><?php echo $this->data[currencies]->format(tep_add_tax($this->data[quotes][$i]['methods'][$j]['cost'], (isset($this->data[quotes][$i]['tax']) ? $this->data[quotes][$i]['tax'] : 0))); ?></strong></td>
        <td align="right" class="radio"><?php echo tep_draw_radio_field('shipping', $this->data[quotes][$i]['id'] . '_' . $this->data[quotes][$i]['methods'][$j]['id'], $checked); ?></td>

<?php
            } else {//echo $this->data[quotes][$i]['methods'][$j]['cost'];
?>

        <td align="right"  colspan="2"><?php //echo $this->data[currencies]->format(tep_add_tax($this->data[quotes][$i]['methods'][$j]['cost'], (isset($this->data[quotes][$i]['tax']) ? $this->data[quotes][$i]['tax'] : 0))) . tep_draw_hidden_field('shipping', $this->data[quotes][$i]['id'] . '_' . $this->data[quotes][$i]['methods'][$j]['id']);

		echo $this->data[currencies]->format(tep_add_tax($this->data[quotes][$i]['methods'][$j]['cost'], (isset($this->data[quotes][$i]['tax']) ? $this->data[quotes][$i]['tax'] : 0))) . tep_draw_radio_field('shipping', $this->data[quotes][$i]['id'] . '_' . $this->data[quotes][$i]['methods'][$j]['id'], 'checked');		?></td>

<?php
            }
?>

      </tr>

<?php
            $radio_buttons++;
          }
        }
      }
    }
?>

    </table>
  </div>

<?php
  }
?><!-- <input type="submit" name="submit" value="submit"> -->
<div class="buttons">
  <div class="right">
<a class="button_btn" id="button-shipping"><span>Continue</span></a></div>
</div>
                    </form>          <!--chkOutConient_block --></div>
                          <!--chkOutContent --></div>
