<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>

                	<div id="content"><!--content start-->
					
					<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>
					
<div class="breadcrumb"><!--readcrumb start-->
                    	<p><?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?>                   </p> <!--readcrumb End --></div>

                    <div class="page-title"><h1><? echo $_SESSION['OBJ']['tr']->translate('heading_title_checkout_voucher');?></h1></div>

						<div class="box">
						
						
		 <div class="box-content">				
<?php if ($this->data[error_warning]) { ?>
  <div class="warning"><?php echo $this->data[error_warning]; ?></div>
  <?php } ?>
  <p><?php echo $_SESSION['OBJ']['tr']->translate('text_description_checkout_voucher'); ?></p>
  <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="voucher">
    <table class="form">
      <tr>
        <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_to_name_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><input type="text" name="to_name" value="<?php echo $this->data[to_name]; ?>" />
          <?php if ($this->data[error_to_name]) { ?>
          <span class="error"><?php echo $this->data[error_to_name]; ?></span>
          <?php } ?></td>
      </tr>
      <tr>
        <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_to_email_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><input type="text" name="to_email" value="<?php echo $this->data[to_email]; ?>" />
          <?php if ($this->data[error_to_email]) { ?>
          <span class="error"><?php echo $this->data[error_to_email]; ?></span>
          <?php } ?></td>
      </tr>
      <tr>
        <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_from_name_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><input type="text" name="from_name" value="<?php echo $this->data[from_name]; ?>" />
          <?php if ($this->data[error_from_name]) { ?>
          <span class="error"><?php echo $this->data[error_from_name]; ?></span>
          <?php } ?></td>
      </tr>
      <tr>
        <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_from_email_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><input type="text" name="from_email" value="<?php echo $this->data[from_email]; ?>" />
          <?php if ($this->data[error_from_email]) { ?>
          <span class="error"><?php echo $this->data[error_from_email]; ?></span>
          <?php } ?></td>
      </tr>
      <tr>
        <td><?php echo $_SESSION['OBJ']['tr']->translate('entry_message_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><textarea name="message" cols="40" rows="5"><?php echo $this->data[message]; ?></textarea></td>
      </tr>
      <tr>
        <td><span class="required">*</span> <?php echo $this->data[entry_amount]; ?></td>
		 <td align="left" valign="middle">:</td>
        <td><input type="text" name="amount" value="<?php echo $this->data[amount]; ?>" size="5" />
          <?php if ($this->data[error_amount]) { ?>
          <span class="error"><?php echo $this->data[error_amount]; ?></span>
          <?php } ?></td>
      </tr>
      <tr>
        <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_theme_checkout_voucher'); ?></td>
		 <td align="left" valign="middle">:</td>
        <td><?php foreach ($this->data[voucher_themes] as $voucher_theme) { ?>
          <?php if ($voucher_theme['voucher_theme_id'] == $this->data[voucher_theme_id]) { ?>
          <input type="radio" class="radio" name="voucher_theme_id" value="<?php echo $voucher_theme['voucher_theme_id']; ?>" id="voucher-<?php echo $voucher_theme['voucher_theme_id']; ?>" checked="checked" />
          <label for="voucher-<?php echo $voucher_theme['voucher_theme_id']; ?>"><?php echo $voucher_theme['name']; ?></label>
          <?php } else { ?>
          <input type="radio" class="radio" name="voucher_theme_id" value="<?php echo $voucher_theme['voucher_theme_id']; ?>" id="voucher-<?php echo $voucher_theme['voucher_theme_id']; ?>" />
          <label for="voucher-<?php echo $voucher_theme['voucher_theme_id']; ?>"><?php echo $voucher_theme['name']; ?></label>
          <?php } ?>
          <br />
          <?php } ?>
          <?php if ($this->data[error_theme]) { ?>
          <span class="error"><?php echo $this->data[error_theme]; ?></span>
          <?php } ?></td>
      </tr>
	  <tr>
	   <td></td>
	    <td align="left" valign="middle"></td>
	   <td height="100"><div class="right">
	  <p><label for="agree">
        <?php if ($this->data[agree]) { ?>
        <input type="checkbox" name="agree" id="agree"  value="1" class="radio" checked="checked" />
        <?php } else { ?>
        <input type="checkbox" class="radio"  name="agree" id="agree" value="1" />
        <?php } ?>
		<span><?php echo $_SESSION['OBJ']['tr']->translate('text_agree_checkout_voucher'); ?></span></label>
		</p>
        <a onclick="$('#voucher').submit();" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_submit_checkout_voucher'); ?></span></a></div></td>
		</tr>
	  
    </table>
<!--    <div class="buttons">
     
    </div>-->
  </form>		 </div>
		 </div>

		    </div>



                <!--rightContainer -->
<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>			</div>
            <!--innerContent --></div>
    	<!--contentArea -->
