<!--<script type="text/javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jshashtable-2.1_src.js"></script>

<div class="box">
<div class="categories-div">
<div class="box-heading"><p><span>Price</span></p></div>
<div class="box-content">
	<div class="price-search">
   <div class="layout-slider" style="width: 100%">
      <span class="slider"><input id="Slider1" type="slider" name="price" value="30000.5;60000" /></span>  
    </div>
    <script type="text/javascript" charset="utf-8">
      jQuery("#Slider1").slider({ from: 10, to: 100000, step: 500, smooth: true, round: 0, dimension: "&nbsp;$", skin: "plastic" });
    </script>
	</div>
</div>
</div>
</div>-->