    <div class="box">
	   <div class="box-newsletter">
    <div class="box-content">
 
	
		
     <div class="newsletter">
	 <h2>Newsletter</h2>
	 <p>Add your email address to receive our newsletters.</p>
	 <div class="search">
	<input name="newsletter_email" id="newsletter_email"  type="text" class="search-text" value=""/>
	<div class="search-icon"><a herf="" class="sub-btn"></a></div>
	 </div>
	 </div>
	 
 
			</div>
		</div>
	</div>