<!-- start single bottom rightbar -->
<div class="content_bottom_right">
                <div class="single_bottom_rightbar">
                  <?php if(@constant('featured_module_title')!=""){ ?><h2><?php echo @constant('featured_module_title'); ?></h2><? } ?>
                  <ul class="small_catg popular_catg wow fadeInDown">
                    <?php foreach ($this->info[data][products] as $product) { ?> 
						<li>
                      <div class="media wow fadeInDown">
                        <a href="#" class="media-left">
                          <img alt="img" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/112x112.jpg">
                        </a>
                        <div class="media-body">
                          <h4 class="media-heading"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h4> 
                          <div class="media-body">
								<h4 class="media-heading"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h4> 
								<div class="comments_box">
									<span class="meta_date">14/12/2013</span>
									<span class="meta_comment"><a href="#">No Comments</a></span>
								</div>
							</div>
                        </div>
                      </div>
                    </li>
					<? } ?>
                    
                  </ul>
				  </div>
                </div> <!-- End single bottom rightbar -->
<?/*?>
<!-- start technology category area --> 
<div class="technology_catrarea">
	<div class="single_category">
		<h2>                  
			<span class="bold_line"><span></span></span>
			<span class="solid_line"></span>
			<?php if(@constant('featured_module_title')!=""){ ?><a class="title_text"><?php echo @constant('featured_module_title'); ?></a><?}?>
			
		</h2>
		<div class="business_category_left">
			<ul class="fashion_catgnav wow fadeInDown">
				<li>
					<div class="catgimg2_container">
						<a href="#"><img alt="img" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/390x240x1.jpg"></a>
					</div>
					<h2 class="catg_titile"><a href="#">Aenean mollis metus sit amet ligula adipiscing</a></h2>
					<div class="comments_box">
						<span class="meta_date">14/12/2013</span>
						<span class="meta_comment"><a href="#">No Comments</a></span>
						<span class="meta_more"><a  href="#">Read More...</a></span>
					</div>
					<p>Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla...</p>
				</li>
			</ul>
		</div>  
		<div class="business_category_right">
			<ul class="small_catg wow fadeInDown">
				<?php foreach ($this->info[data][products] as $product) { ?> 
					
					<!--<pre>
						<?php //print_r($product);?>
					</pre>-->
					<li>
						<div class="media wow fadeInDown">
							<a class="media-left" href="#">
								<img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/112x112.jpg" alt="img">
							</a>
							<div class="media-body">
								<h4 class="media-heading"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h4> 
								<div class="comments_box">
									<span class="meta_date">14/12/2013</span>
									<span class="meta_comment"><a href="#">No Comments</a></span>
								</div>
							</div>
						</div>
					</li>
				<? } ?>
				
			</ul>
		</div>   
	</div>
</div><!-- End technology category area --><? } */?>