    <div class="box">
	   <div class="box-flow">
	   <div class="modules-box-div">
<div class="box-content">
<div class="flow">
<p><span>Followus </span> <a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/images/tw-icon.png" /></a>
	 <a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/images/you-icon.png" /></a></p>
	
				</div></div>
			</div>
		</div>
	</div>