<!-- <div class="welcome"><?php echo $heading_title; ?></div>
<?php echo $message; ?> -->
<div id="leftmenuBG_btm">
                    	<div id="leftmenuBG_top">
						<div class="modules-box-div">
                        	<div id="leftmenu_Categories">
                            	<div class="categ"><h1>Popular Tags</h1></div>
                                	 <div class="inner-div"><div id="topbrands">
                                    	Sumsung  iMAC Systems Fujifilm Cameras Nokia iPhone Adobe Reliance Khazana Sony  LG  Seamans   Nike
                                    </div>
                                    </div>
                            <!--leftmenu_Categories --></div>
                        <!--leftmenuBG_top --></div></div>
                		<!--leftmenuBG_btm --></div>
                	<!--leftcontainer -->