
<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?></P>
                   <!--readcrumb End --></div>
				    <!-- <div class="page-title"><h1><?php echo $_SESSION['OBJ']['tr']->translate('heading_title_account_address');?></h1></div>-->
							 
                    
					 <div class="box">
				  <div class="box-heading"><p><span><?php echo $_SESSION['OBJ']['tr']->translate('text_address_book_account_address');?></span></p></div>
				  <div class="box-content" >
                    	 <?php if ($this->data[success]) { ?>
  <div class="success"><?php echo $this->data[success]; ?></div>
  <?php } ?>
  <?php if ($this->data[error_warning]) { ?>
  <div class="warning"><?php echo $this->data[error_warning]; ?></div>
  <?php } ?>
 <!-- <h2><?php echo $this->data[text_address_book]; ?></h2>-->
  <?php 

  foreach ($this->data[addresses] as $result) { ?>
 		 
                    
					 <div class="box">
				  
				  <div class="box-address" id="address-info">
    <table style="width: 100%;">
      <tr>
        <td><?php echo $result['address']; ?></td>
        <td class="right-div-list" ><a href="<?php echo $result['update']; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_edit'); ?></span></a> &nbsp; <a href="<?php echo $result['delete']; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_delete'); ?></span></a></td>
      </tr>
    </table>
	</div>
  </div> 
  <?php } ?>
  <div class="buttons">
    <div class="left"><a href="<?php echo $this->data[back]; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_back'); ?></span></a></div>
    <div class="right"><a href="<?php echo $this->data[insert]; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_new_address'); ?></span></a></div>
  </div>
                    <!--innerpage_rightContent --></div>
				<?if(count($this->pos[bottom])>0){?>
				<div class="container-top">
				<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?></div>
				<?}?>	
                <!--rightContainer --></div>
            <!--innerContent --></div>