<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

               <div class="breadcrumb"><!--readcrumb start-->
<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?></p>
                  <!--readcrumb End --></div>
				
					 <div class="page-title">
<h1><span><?php echo $this->trans->_('text_edit_account_edit'); ?></span> </h1></div>
     	
                    
   <?php if ($this->data[error_warning]) { ?>
  <div class="warning"><?php echo $this->data[error_warning]; ?></div>
  <?php } ?>
  <div class="box">
  <div class="box-account-edit">
  <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="edit">

<div class="box-content">
<div class="content">
<h4><?php echo $this->trans->_('text_your_details_account_edit');?></h4>
      <table class="form">
	  
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_firstname_account_edit'); ?></td>
          <td><input type="text" name="firstname" value="<?php echo $this->data[firstname]; ?>" />
            <?php if ($this->data[error_firstname]) { ?>
            <span class="error"><?php echo $this->data[error_firstname]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_lastname_account_edit'); ?></td>
          <td><input type="text" name="lastname" value="<?php echo $this->data[lastname]; ?>" />
            <?php if ($this->data[error_lastname]) { ?>
            <span class="error"><?php echo $this->data[error_lastname]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_email_account_edit'); ?></td>
          <td><input type="text" name="email" value="<?php echo $this->data[email]; ?>" />
            <?php if ($this->data[error_email]) { ?>
            <span class="error"><?php echo $this->data[error_email]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_telephone_account_edit'); ?></td>
          <td><input type="text" name="telephone" value="<?php echo $this->data[telephone]; ?>" />
            <?php if ($this->data[error_telephone]) { ?>
            <span class="error"><?php echo $this->data[error_telephone]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><?php echo $this->trans->_('entry_fax_account_edit'); ?></td>
          <td><input type="text" name="fax" value="<?php echo $this->data[fax]; ?>" /></td>
        </tr>
      </table>
    </div>
	  </div>
	    </div>
    <div class="buttons">
      <div class="left"><a href="<?php echo $this->data[back]; ?>" class="button_btn"><span><?php echo $this->trans->_('button_back'); ?></span></a></div>
      <div class="right"><a onclick="$('#edit').submit();" class="button_btn"><span><?php echo $this->trans->_('button_submit_account_edit'); ?></span></a></div>
    </div>
  </form>
 </div>						
						</div>
                   <!--box end --> </div>
<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
                            
<!--container End--></div>
           <!--main-max-banner End--></div>