<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

             <div class="breadcrumb"><!--readcrumb start-->
<p>  <?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?></p>
		 <!--readcrumb End --></div>
		 
		 
                     <div class="page-title"><h1><span> <?php echo $this->trans->_('heading_title_account_order'); ?></span></h1></div>
						 
                    	<div class="box">
						
<div class="box-content">


      <?php if ($this->data[orders]) { ?>
        <div class="pagination"><?php echo $this->data[pagination]; ?></div>

  <?php foreach ($this->data[orders] as $order) { ?>
  <div class="order-list">
    <div class="list-title-bar">
    <div class="order-id"><b><?php echo $this->trans->_('text_order_id_account_order'); ?></b> #<?php echo $order['order_id']; ?></div>
    <div class="order-status"><b><?php echo $this->trans->_('text_status_account_order'); ?></b> <?php echo $order['status']; ?></div>
	</div>
    <div class="order-content">
      <div><b><?php echo $this->trans->_('text_date_added_account_order'); ?></b> <?php echo $order['date_added']; ?><br />
        <b><?php echo $this->trans->_('text_products_account_order'); ?></b> <?php echo $order['products']; ?></div>
      <div><b><?php echo $this->trans->_('text_customer_account_order'); ?></b> <?php echo $order['name']; ?><br />
        <b><?php echo $this->trans->_('text_total_account_order'); ?></b> <?php echo $order['total']; ?></div>
      <div class="order-info"><a href="<?php echo $order['href']; ?>" class="button_btn"><span><?php echo $this->trans->_('button_view'); ?></span></a></div>
    </div>
  </div>
  <?php } ?>
  <div class="pagination"><?php echo $this->data[pagination]; ?></div>
  <?php } else { ?>
  <div class="content"><?php echo $this->trans->_('text_empty_account_order'); ?></div>
  <?php } ?>
 
  <?php echo $this->data[content_bottom]; ?></div>

                   <!--box end --></div>
	
					
<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
                            
<!--container End--></div>
           <!--main-max-banner End--></div>