<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>

                	<div id="content"><!--content start-->
					
					<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>
					
<div class="breadcrumb"><!--readcrumb start-->
                    	<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?> </p> <!--readcrumb End --></div>
				  
				  
				  
                   <div class="page-title"><h1><?php echo $this->data[heading_title]; ?></h1></div>
 <?php echo $_SESSION['OBJ']['tr']->_('text_description_account_return'); ?>
                    	<div class="box">
						
						
			
			<div class="box-heading"><?php echo $_SESSION['OBJ']['tr']->_('text_order_account_return'); ?></div>
			 
			 <div class="box-content">
			 
  <form name="frmreturn"  id="frmreturn" action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data">
    
    <div class="content">
      <div class="left">
	  
	  <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->_('entry_firstname_account_return'); ?></div>
       <div class="contact-textbox"><input type="text" name="firstname" value="<?php echo $this->data['firstname']; ?>" class="large-field" />
       <br/>
        <?php if ($this->data[error_firstname]) { ?>
        <span class="error"><?php echo $this->data[error_firstname]; ?></span>
        <?php } ?>
        </div>
		<div id="clear"></div>
		</div>
          <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->_('entry_lastname_account_return'); ?></div>
         <div class="contact-textbox"> <input type="text" name="lastname" value="<?php echo $this->data[lastname]; ?>" class="large-field" />
        <br />
        <?php if ($this->data[error_lastname]) { ?>
        <span class="error"><?php echo $this->data[error_lastname]; ?></span>
        <?php } ?>
		</div>
		<div id="clear"></div>
		</div>
         <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->_('entry_email_account_return'); ?></div>
        <div class="contact-textbox">  <input type="text" name="email" value="<?php echo $this->data[email]; ?>" class="large-field" />
        <br />
        <?php if ($this->data[error_email]) { ?>
        <span class="error"><?php echo $this->data[error_email]; ?></span>
        <?php } ?>
	</div>
	<div id="clear"></div>
		</div>
         <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->_('entry_telephone'); ?></div>
       <div class="contact-textbox">  <input type="text" name="telephone" value="<?php echo $this->data[telephone]; ?>" class="large-field" />
        <br />
        <?php if ($this->data[error_telephone]) { ?>
        <span class="error"><?php echo $this->data[error_telephone]; ?></span>
        <?php } ?>
      	</div>
		<div id="clear"></div>
		</div>
		
      </div>
	  
      <div class="right">
	  
	  <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->_('entry_order_id_account_return'); ?></div>
          <div class="contact-textbox"> <input type="text" name="order_id" value="<?php echo $this->data[order_id]; ?>" class="large-field" />
        <br />
        <?php if ($this->data[error_order_id]) { ?>
        <span class="error"><?php echo $this->data[error_order_id]; ?></span>
        <?php } ?>
   </div>
   <div id="clear"></div>
		</div>
        
		 <div class="contact-form">
	  <div class="contact-name"><?php echo $_SESSION['OBJ']['tr']->_('entry_date_ordered_account_return'); ?></div>
        <div class="contact-textbox"><input type="text" name="date_ordered" value="<?php echo $this->data[date_ordered]; ?>" class="large-field date" />
      </div> 
	  <div id="clear"></div>
	  </div>
	  
      </div>
    </div>
	
    <h2><?php echo $_SESSION['OBJ']['tr']->_('text_product_account_return'); ?></h2>
    <div id="return-product">
      <div class="content">
        <div class="return-product">
          <div class="return-name">
		 <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <b><?php echo $_SESSION['OBJ']['tr']->_('entry_product_account_return'); ?></b></div>
            <div class="contact-textbox"> <input type="text" name="product" value="<?php echo $this->data['product']; ?>" />
            <br />
            <?php if ($this->data[error_product]) { ?>
            <span class="error"><?php echo $this->data[error_product]; ?></span>
            <?php } ?>
			 </div>
			 <div id="clear"></div>
    </div>
          </div>
          <div class="return-model">
		  
		   <div class="contact-form">
	  <div class="contact-name"><span class="required">*</span> <b><?php echo $_SESSION['OBJ']['tr']->_('entry_model_account_return'); ?></b></div>
              <div class="contact-textbox"> <input type="text" name="model" value="<?php echo $this->data[model]; ?>" />
            <br />
            <?php if ($this->data[error_model]) { ?>
            <span class="error"><?php echo $this->data[error_model]; ?></span>
            <?php } ?>
				 </div>
				 <div id="clear"></div>
    </div>
          </div>
          <div class="return-quantity">
		    <div class="contact-form">
		 <div class="contact-name"> <b><?php echo $_SESSION['OBJ']['tr']->_('entry_quantity_account_return'); ?></b></div>
            <div class="contact-textbox"><input type="text" name="quantity" value="<?php echo $this->data[quantity]; ?>" />
          </div>
		  <div id="clear"></div>
        </div>
		    </div>
			
        <div class="return-detail">
          <div class="return-reason">
		  
		 <div class="contact-form">
		 <div class="contact-name"> <span class="required">*</span> <b><?php echo $_SESSION['OBJ']['tr']->_('entry_reason_account_return'); ?></b></div>
        <div class="contact-textbox"> <table>
              <?php foreach ($this->data[return_reasons] as $return_reason) { ?>
              <?php if ($return_reason['return_reason_id'] == $this->data[return_reason_id]) { ?>
              <tr>
                <td width="1"><input type="radio" class="checkbox" name="return_reason_id" value="<?php echo $return_reason['return_reason_id']; ?>" id="return-reason-id<?php echo $return_reason['return_reason_id']; ?>" checked="checked" /></td>
                <td><label for="return-reason-id<?php echo $return_reason['return_reason_id']; ?>"><?php echo $return_reason['name']; ?></label></td>
              </tr>
              <?php } else { ?>
              <tr>
                <td width="1"><input type="radio" class="checkbox" name="return_reason_id" value="<?php echo $return_reason['return_reason_id']; ?>" id="return-reason-id<?php echo $return_reason['return_reason_id']; ?>" /></td>
                <td><label for="return-reason-id<?php echo $return_reason['return_reason_id']; ?>"><?php echo $return_reason['name']; ?></label></td>
              </tr>
              <?php  } ?>
              <?php  } ?>
            </table>
            <?php if ($this->data[error_reason]) { ?>
            <span class="error"><?php echo $this->data[error_reason]; ?></span>
            <?php } ?>
			 </div>
			 <div id="clear"></div>
			 </div>
          </div>
		  
		  
          <div class="return-opened">
		  
		 <div class="contact-form">
		 <div class="contact-name"> <b><?php echo $_SESSION['OBJ']['tr']->_('entry_opened_account_return'); ?></b></div>
        <div class="contact-textbox">       <?php if ($this->data[opened]) { ?>
            <input type="radio" name="opened" class="checkbox" value="1" id="opened" checked="checked" />
            <?php } else { ?>
            <input type="radio" name="opened" class="checkbox" value="1" id="opened" />
            <?php } ?>
			<label for="opened"><?php echo $_SESSION['OBJ']['tr']->_('text_yes'); ?></label></div>
              <div class="contact-textbox"><?php if (!$this->data[opened]) { ?>
            <input type="radio" name="opened" class="checkbox" value="0" id="unopened" checked="checked" />
            <?php } else { ?>
            <input type="radio" name="opened" class="checkbox" value="0" id="unopened" />
            <?php } ?>

		  
        <label for="unopened"><?php echo $_SESSION['OBJ']['tr']->_('text_no'); ?></label>
					 </div>
			 <div id="clear"></div>
			 </div>
          </div>
		  
            <div class="return-captcha">
			<div class="contact-form">
           <div class="contact-name"><?php echo $_SESSION['OBJ']['tr']->_('entry_fault_detail_account_return'); ?></div>
              <div class="contact-form"><textarea name="comment" cols="150" rows="6"><?php echo $this->data[comment]; ?></textarea></div>
			 <div id="clear"></div>
			 </div>
          </div>
		  
		  
           <div class="return-captcha-1">
			<div class="contact-form">
		 <div class="contact-name"><b><?php echo $_SESSION['OBJ']['tr']->_('entry_captcha_account_return'); ?></b></div>
		 
		  
            <div class="contact-textbox"> <input type="text" name="captcha" value="<?php echo $this->data[captcha]; ?>" />
            <br />
            <img src="<?php echo HTTP_SERVER.'product/captcha';?>" alt="" />
            <?php if ($this->data[error_captcha]) { ?>
            <span class="error"><?php echo $this->data[error_captcha]; ?></span>
            <?php } ?>
			</div>
			 <div id="clear"></div>
			 </div>
          </div>
        </div>
      </div>
    </div>
	 </div>

			
			</div>
                    <!--innerpage_rightContent --></div>
					
					    <div class="buttons">
      <div class="left"><a href="<?php echo $this->data[back]; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->_('button_back'); ?></span></a></div>
      <div class="right">
        <!--<input type="submit" value="<?php echo $_SESSION['OBJ']['tr']->_('button_continue'); ?>" class="button" />-->
		<a class="button_btn" onclick="document.frmreturn.submit();">
<span>Continue</span>
</a>
      </div>
    </div>
  </form>

					
		<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
                <!--rightContainer --></div>
            <!--innerContent --></div>