<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?>
                  <!--readcrumb End --></div>
				  
				  
                          <div class="page-title">
<h1> <?php echo $this->trans->_('heading_title_account_reward'); ?></h1></div>
<div class="box">
<div class="reward-box-main">
				  <div class="box-content">
				  
						 <p><?php echo $this->trans->_('text_total_account_reward'); ?><b> <?php echo $this->data[total]; ?></b>.</p>
  <table class="list">
    <thead>
      <tr>
        <td class="dashBar"><?php echo $this->trans->_('column_date_added_account_reward'); ?></td>
        <td class="dashBar"><?php echo $this->trans->_('column_description_account_reward'); ?></td>
        <td class="dashBar"><?php echo $this->trans->_('column_points_account_reward'); ?></td>
      </tr>
    </thead>
    <tbody>
      <?php if ($this->data[rewards]) { ?>
      <?php foreach ($this->data[rewards]  as $reward) { ?>
      <tr>
        <td class="dashgrid"><?php echo $reward['date_added']; ?></td>
        <td class="dashgrid"><?php if ($reward['order_id']) { ?>
          <a href="<?php echo $reward['href']; ?>"><?php echo $reward['description']; ?></a>
          <?php } else { ?>
          <?php echo $reward['description']; ?>
          <?php } ?></td>
        <td class="dashgrid"><?php echo $reward['points']; ?></td>
      </tr>
      <?php } ?>
      <?php } else { ?>
      <tr>
        <td class="center" colspan="5"><?php echo $this->trans->_('text_empty_account_reward'); ?></td>
      </tr>
      <?php } ?>
    </tbody>
  </table>
  <div class="pagination"><?php echo $this->data[pagination]; ?></div>


						</div>
						</div>
                       <!--box end --></div>
					<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
                          
<!--container End--></div>
           <!--main-max-banner End--></div>