<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>

                    	<?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?></p>                    <!--readcrumb End --></div>

                  <div class="page-title"><h1>  <? echo $this->data[heading_title];?></h1></div>
				  
						  <div class="box">
				   <div class="box-content-main">
				  <div class="box-content">
		 <?php echo $this->data[text_message_success]; ?>
		 </div>
		 </div>
		 </div>
		 		  <!-- <div class="buttons">
    <div class="right"><a href="<?php echo $this->data['continue']; ?>" class="button_btn"><span><?php echo $this->trans->_('button_continue'); ?></span></a></div>
  </div> -->
		 </div>


                  <!--box end --></div>

<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
              
<!--container End--></div>
           <!--main-max-banner End--></div>
