<?/*echo "<pre>";
print($this->data[shipping_required]);
echo "</pre>";*/?>
<div id="chkOutContainer">


<!--start guest shipping  -->
<?php if ($this->data[shipping_required]!="") { ?>
	<div id="chkOutContent-right" class="chkOutContent-right">
		<div id="caption"><p><?php echo $_SESSION['OBJ']['tr']->translate('text_checkout_shipping_address_checkout_checkout');?></p></div>
	<div id="chkOutConient_block">
<table class="form" id="guest_ship">
<!-- <tr class="use_billing_row">
          <td colspan="2" class="same_as_ship"><input type="checkbox" class="checkbox_default" name="useShippingInfoForBillingInfo" id="useShippingInfoForBillingInfo">
            <label for="useShippingInfoForBillingInfo">Same as Billing Address</label>
          </td>
        </tr> -->
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_firstname_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_firstname" value="<?php echo $this->data[shipping_firstname]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_lastname_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_lastname" value="<?php echo $this->data[shipping_lastname]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><?php echo $_SESSION['OBJ']['tr']->translate('entry_company_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_company" value="<?php echo $this->data[shipping_company]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_address_1_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_address_1" value="<?php echo $this->data[shipping_address_1]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><?php echo $_SESSION['OBJ']['tr']->translate('entry_address_2_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_address_2" value="<?php echo $this->data[shipping_address_2]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_city_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_city" value="<?php echo $this->data[shipping_city]; ?>" class="large-field" /></td>
  </tr>
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_postcode_checkout_checkout'); ?></td>
    <td><input type="text" name="shipping_postcode" value="<?php echo $this->data[shipping_postcode]; ?>" class="large-field" /></td>
  </tr>
   <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_country_checkout_checkout'); ?></td>
    <td>
    <select name="shipping_country_id" class="large-field" onchange="$('#guest_ship select[name=\'shipping_zone_id\']').load('<?echo $this->view->url_to_site;?>ajax/zone/country_id/' + this.value);">
        <option value=""><?php echo $_SESSION['OBJ']['tr']->translate('text_select'); ?></option>
        <?php foreach ($this->data[countries] as $country) { ?>
        <?php if ($country['countries_id'] == $this->data[shipping_country_id]) { ?>
        <option value="<?php echo $country['countries_id']; ?>" selected="selected"><?php echo $country['countries_name']; ?></option>
        <?php } else { ?>
        <option value="<?php echo $country['countries_id']; ?>"><?php echo $country['countries_name']; ?></option>
        <?php } ?>
        <?php } ?>
      </select></td>
  </tr>
  <tr>
    <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_zone_checkout_checkout'); ?></td>
    <td><select name="shipping_zone_id" class="large-field">
      </select></td>
  </tr>
</table>
<br />
</div>
		<div id="shipping_address"></div>
		<div id="shipping_method"></div>
</div>
<?}?>
	<!--end guest shipping  -->
   
	<div id="chkOutContent" class="chkOutContent-div">
	 <div id="caption"><p><?php echo $_SESSION['OBJ']['tr']->translate('text_checkout_payment_address_checkout_checkout');?></p></div>
		<div id="chkOutConient_block">
		<!--content start  -->
		<div class="checkout-main">
		<div class="left">
  <h4><?php echo $_SESSION['OBJ']['tr']->translate('text_your_details_checkout_checkout'); ?></h4>
<div class="names" > <span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_firstname_checkout_checkout'); ?></div>
 <div class="names-text"> <input type="text" name="firstname" value="<?php echo $this->data[firstname]; ?>" class="large-field" />
 </div>


  <div class="names"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_lastname_checkout_checkout'); ?></div>
  <div class="names-text">  <input type="text" name="lastname" value="<?php echo $this->data[lastname]; ?>" class="large-field" /></div>

  <div class="names"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_email_checkout_checkout'); ?></div>
  <div class="names-text"> <input type="text" name="email" value="<?php echo $this->data[email]; ?>" class="large-field" /></div>

 <div class="names"> <span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_telephone_checkout_checkout'); ?></div>
<div class="names-text"><input type="text" name="telephone" value="<?php echo $this->data[telephone]; ?>" class="large-field" /></div>

 <div class="names"> <?php echo $_SESSION['OBJ']['tr']->translate('entry_fax_checkout_checkout'); ?></div>
 <div class="names-text"> <input type="text" name="fax" value="<?php echo $this->data[fax]; ?>" class="large-field" /></div>

</div>
<div class="right">
  <h4><?php echo $_SESSION['OBJ']['tr']->translate('text_your_address_checkout_checkout'); ?></h4>
  <div class="names"> <?php echo $_SESSION['OBJ']['tr']->translate('entry_company_checkout_checkout'); ?></div>
 <div class="names-text"> <input type="text" name="company" value="<?php echo $this->data[company]; ?>" class="large-field" /></div>

  <div class="names"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_address_1_checkout_checkout'); ?></div>
  <div class="names-text"> <input type="text" name="address_1" value="<?php echo $this->data[address_1]; ?>" class="large-field" /></div>

 <div class="names"> <?php echo $_SESSION['OBJ']['tr']->translate('entry_address_2_checkout_checkout'); ?></div>
  <div class="names-text"> <input type="text" name="address_2" value="<?php echo $this->data[address_2]; ?>" class="large-field" /></div>

  <div class="names"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_city_checkout_checkout'); ?></div>
   <div class="names-text"><input type="text" name="city" value="<?php echo $this->data[city]; ?>" class="large-field" /></div>

  <div class="names"><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_postcode_checkout_checkout'); ?></div>
   <div class="names-text"><input type="text" name="postcode" value="<?php echo $this->data[postcode]; ?>" class="large-field" /></div>

 <div class="names"> <span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_country_checkout_checkout'); ?></div>
    <div class="names-text"><select name="country_id" class="large-field" onchange="$('#chkOutConient_block select[name=\'zone_id\']').load('<?php echo $this->view->url_to_site;?>ajax/zone/country_id/' + this.value);">


    <option value=""><?php echo $_SESSION['OBJ']['tr']->translate('text_select'); ?></option>
    <?php foreach ($this->data[countries] as $country) { ?>
    <?php if ($country['countries_id'] == $this->data[country_id]) { ?>
    <option value="<?php echo $country['countries_id']; ?>" selected="selected"><?php echo $country['countries_name']; ?></option>
    <?php } else { ?>
    <option value="<?php echo $country['countries_id']; ?>"><?php echo $country['countries_name']; ?></option>
    <?php } ?>
    <?php } ?>
  </select></div>


  <div class="names"> <span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_zone_checkout_checkout'); ?></div>
  <div class="names-text"><select name="zone_id" class="large-field">
  </select></div>
</div>

</div>
<?php if ($this->data[shipping_required]!="") { ?>
<div style="clear: both; padding-top: 15px;  margin-top:6px;  border-top: 1px solid #DDDDDD; text-align:right; ">
  <?php if ($this->data[shipping_address]) { ?>
  <input type="checkbox" name="shipping_address" value="1" id="shipping" checked="checked" />
  <?php } else { ?>
  <input type="checkbox" name="shipping_address" value="1" id="shipping" />
  <?php } ?>
  <label for="shipping"><?php echo $_SESSION['OBJ']['tr']->translate('entry_shipping_checkout_checkout'); ?></label>



</div>
<?php } ?>

<!-- <div class="buttons">
  <div class="right"><a id="button-guest" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_continue'); ?></span></a></div>
</div> -->
<script type="text/javascript"><!--
$('select[name=\'zone_id\']').load('<?php echo $this->view->url_to_site;?>ajax/zone/country_id/<?php echo $this->data[country_id]; ?>/zone_id/<?php echo $this->data[zone_id]; ?>');
//--></script>


		<!--content end  -->
		</div>
		<div id="shipping_address"></div>
		<div id="shipping_method"></div>
	</div>
<div class="buttons">
  <div class="right"><a id="button-guest" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_continue'); ?></span></a></div>
</div>
	


<script type="text/javascript"><!--
$('#guest_ship select[name=\'shipping_zone_id\']').load('<?php echo $this->view->url_to_site;?>ajax/zone/country_id/<?php echo $this->data[country_id]; ?>/zone_id/<?php echo $this->data[shipping_zone_id]; ?>');
//--></script>