<?
if(sizeof($this->info[data][category])>0) //check if a category has products and display only if category has products
{
foreach($this->info[data][category] as $k=>$v){
$exp=explode("#",$k);
$cat_name=$exp[0];
$cat_id=$exp[1];
?>

  <div class="box">
    <div class="categoryproduct-box">
	<div class="modules-box-div">
   <div class="box-heading"><p><span><?php echo $cat_name;?></a></span><span class="right-div"><a href="<?php echo $this->url_to_site."product/category/path/".$cat_id;?>".>[view all]</a></span></div>
    <div class="box-content">
    <div class="box-product">
	
			  <?php foreach ($v as $product) { ?>
      <div>
        <?php if ($product['thumb']) { ?>
        <div class="image"><a href="<?php echo $product['href']; ?>"><img src="<?php echo $this->url_to_site."timthumb.php?src=".$product['thumb']; ?>" alt="<?php echo $product['name']; ?>" /></a></div>
		
        <?php } ?>
        <div class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></div>
        <?php if ($product['price']) { ?>
        <div class="price">
          <?php if (!$product['special']) { ?>
          <?php echo $product['price']; ?>
          <?php } else { ?>
          <span class="price-old"><?php echo $product['price']; ?></span> <span class="price-new"><?php echo $product['special']; ?></span>
          <?php } ?>
        </div>
        <?php } ?>
        <?php if ($product['rating']) { ?>
        <div class="rating"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/rating-<?php echo $product['rating']; ?>.jpg" alt="<?php echo sprintf($this->trans->_('text_reviews_product_product'), (int)$product['reviews']); ?>" /></div>
        <?php } ?>
       <div class="cart"><a  href="javascript:addToCart('<?php echo $product['product_id']; ?>');"  class="button"><span><?php echo $this->trans->_($this->info[data][button_cart]); ?></span> </a></div>
      </div>
      <?php } ?>
			</div>
		</div></div></div>
	</div>
<?}}?>