    <div class="box">
		<div class="modules-box-div">
	<div class="featured-div">
    <?php if(@constant('featured_module_title')!=""){ ?><div class="box-heading"><p><span><?php echo @constant('featured_module_title'); ?></span></p></div><?}?>
	<div class="featured-div-content">

    <div class="box-content">
    <div class="box-product">
	
			  <?php foreach ($this->info[data][products] as $product) { ?>
      <div>
        <?php if ($product['thumb']) { ?>
        <div class="image"><a href="<?php echo $product['href']; ?>"><img src="<?php echo $this->url_to_site."timthumb.php?src=".$product['thumb']; ?>" alt="<?php echo $product['name']; ?>" /></a></div>
		
        <?php } ?>
		<div class="main-box-left">
        <div class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></div>
		
        <?php if ($product['price']) { ?>
        <div class="price">
          <?php if (!$product['special']) { ?>
          <p class="price-dsplay"> <?php echo $product['price']; ?></p>
          <?php } else { ?>
          <span class="price-old"><?php echo $product['price']; ?></span> <span class="price-new"><?php echo $product['special']; ?></span>
          <?php } ?>
        </div>
        <?php } ?>
        <?php if ($product['rating']) { ?>
        <div class="rating"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/rating-<?php echo $product['rating']; ?>.jpg" alt="<?php echo sprintf($this->trans->_('text_reviews_product_product'), (int)$product['reviews']); ?>" /></div>
        <?php } ?>
       <div class="cart"><a  href="javascript:addToCart('<?php echo $product['product_id']; ?>');"  class="button"><span><?php echo $this->trans->_($this->info[data][button_cart]); ?></span> </a></div>
      </div>
	  </div>
      <?php } ?>
			</div>
		</div></div>
	</div>
  </div>
</div>