<?php
/*echo "<pre>";
print_r($this->info[data]);
echo "</pre>";
exit;*/
?>
<div class="box">
<div class="categories-div">
<div class="modules-box-div">
<?php if($this->info[data][title]!="") {?><dt class="box-heading"><p><span><?php echo $this->info[data][title];?></span></p></dt><?}?>
	<div class="categories-linkes">
		<div class="box-content">
		<ul>
		
<?php foreach ($this->info[data]['manufacturers'] as $category) { ?>
<li>
<a href="<?php echo $category['href']; ?>"><?php echo $category['name']; ?></a>
</li>
<?php } ?>
</ul>
</div>
		</div>
	</div>
</div></div>



