   		
		    <!-- Scrolled js files -->
<script type="text/javascript" language="javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jquery.carouFredSel-6.1.0-packed.js"></script>
		<script type="text/javascript" language="javascript">
			$(function() {
				//	Scrolled by user interaction
				$('#foo2').carouFredSel({
					auto: false,
					prev: '#prev2',
					next: '#next2',
					pagination: "#pager2",
					mousewheel: true,
					swipe: {
						onMouse: true,
						onTouch: true
					}
				});
				
				$('#foo3').carouFredSel({
					auto: false,
					prev: '#prev3',
					next: '#next3',
					pagination: "#pager3",
					mousewheel: true,
					swipe: {
						onMouse: true,
						onTouch: true
					}
				});
				
			});
		</script>
		
<?if(sizeof($this->info[data][products])>0){?>
   <div class="box">
   	<div class="modules-box-div">
<div class="recently-div">
 <?php if(@constant('recentlyviewed_module_title')!=""){ ?>   <div class="box-heading"><p><span><?php echo @constant('recentlyviewed_module_title'); ?> </p></span></div><?}?>
	<div class="Recently-prodect">
		<div class="box-content">
       		<div class="list_carousel">
              <div class="box-product">
              	<div id="pager2" class="pager"></div>
				<ul id="foo2">
				
			  <?php foreach ($this->info[data][products] as $product) { ?>
      	    <li>
           	 <div>
        <?php if ($product['thumb']) { ?>
        <div class="image"><a href="<?php echo $product['href']; ?>"><img src="<?php echo $this->url_to_site."timthumb.php?src=".$product['thumb']; ?>" alt="<?php echo $product['name']; ?>" /></a></div>
		
        <?php } ?>
        <div class="name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></div>
        <?php if ($product['price']) { ?>
        <div class="price">
          <?php if (!$product['special']) { ?>
          <p class="price-dsplay"><?php echo $product['price']; ?></p>
          <?php } else { ?>
          <span class="price-old"><?php echo $product['price']; ?></span> <span class="price-new"><?php echo $product['special']; ?></span>
          <?php } ?>
        </div>
        <?php } ?>
        <?php if ($product['rating']) { ?>
        <div class="rating"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/rating-<?php echo $product['rating']; ?>.jpg" alt="<?php echo sprintf($this->trans->_('text_reviews_product_product'), (int)$product['reviews']); ?>" /></div>
        <?php } ?>
       <div class="cart"><a  href="javascript:addToCart('<?php echo $product['product_id']; ?>');"  class="button"><span><?php echo $this->trans->_($this->info[data][button_cart]); ?></span> </a></div>
        </div>
       </li>
      <?php } ?>
		
		  
             </ul>
             
				<a id="prev2" class="prev" href="#"></a>
				<a id="next2" class="next" href="#"></a>
			
             </div>
             
       		 </div> </div>
        
        </div>
	</div>
</div>
</div>
<?}?>