<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Site is under Maintenance</title>
<?$main_css_path=file_exists(PATH_TO_FILES."load.css")?$this->url_to_site."public/uploads/".@constant('GLOBAL_DOMAIN_KEY')."/files/load.css":$this->url_to_templates.SITE_DEFAULT_TEMPLATE."/includes/css/load.css";?>
<link href="<?PHP echo $main_css_path;?>" rel="stylesheet" type="text/css" />
<style>
.maint-main .herader{width:800px; height:110px; padding:15px 0px; margin:0px auto;  padding-bottom:60px;  }
</style>
</head>

<body style="">

<div class="main-wrapper-div">
<div class="main-top-menu-div">
.
</div>

<div class="main-header">
<div id="container">
<div class="-div" style=" text-align:center; margin-bottom:30px; " >
<div class="logo" style=" text-align:center; width:100%; height:80px; padding-top:25px; padding-bottom:25px;  top:40px; background:url(../images/bg-bodihcart.png) bottom no-repeat; "  ><img src="<?echo PATH_TO_UPLOADS."image/".STORE_LOGO?>" alt="Logo" /></div>

<div style="clear:both; margin:0px auto;"><h2 style=" font-size:40px; text-align:center; color:#9d9d9d; font-family:Arial, Helvetica, sans-serif; line-height:20px; height:40px; font-size:40px; text-transform: uppercase;
color: #333;
font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
font-size: 60px;
font-weight: lighter;
text-shadow: 0px 2px 0px #000;
margin: 30px 0 0 0;  ">Site is </h2>
  <h2 style=" text-transform: uppercase;
color: #333;
font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
font-weight: lighter;
text-shadow: 0px 2px 0px #000;
margin: 30px 0 0 0; height:60px; font-size: 70px;"> Under Maintenance</h2>
</div>
</div>
</div>

<div class="main-content">
<div class="main-column">
<div id="containera" >


</div>

</div>

</div>

</body>
</html>
