<?php
if ($this->data[reviews]) { ?>
<?php foreach ($this->data[reviews] as $review) { ?>
<div class="content"><b><?php echo $review['author']; ?></b> | <img src="<?php echo URL_TO_TEMPLATES.SITE_DEFAULT_TEMPLATE?>/includes/images/rating-<?php echo $review['rating']; ?>.jpg" alt="<?php echo $review['reviews']; ?>" /><br />
  <?php echo $review['date_added']; ?><br />
  <br />
  <?php echo $review['text']; ?></div>
<?php } ?>
<div class="pagination"><?php echo $this->data[pagination]; ?></div>
<?php } else { ?>
<div class="warning"><?php echo $this->data[text_no_reviews]; ?></div>
<?php } ?>
