<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>
<?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?>                    </p>
  <!--readcrumb End--></div>
  
  <div class="affiliate-account-box">
  
         	<div class="box">
			
			  <?php if ($this->data[success]) { ?>
  <div class="success"><?php echo $this->data[success]; ?></div>
  <?php } ?>
  
<div class="box-heading"><p><span><?php echo $this->trans->_('text_my_account_affiliate_account'); ?></span></p></div>


<div class="box-content">
    <ul>
      <li><a href="<?php echo $this->data[edit]; ?>"><?php echo $this->trans->_('text_edit_affiliate_account'); ?></a></li>
      <li><a href="<?php echo $this->data[password]; ?>"><?php echo $this->trans->_('text_password_affiliate_account'); ?></a></li>
      <li><a href="<?php echo $this->data[payment]; ?>"><?php echo $this->trans->_('text_payment_affiliate_account'); ?></a></li>
    </ul>
  </div>
    </div>
	
	
	  	<div class="box">
<div class="box-heading"><p><span><?php echo $this->trans->_('text_my_tracking_affiliate_account'); ?></span></p></div>
<div class="box-content">
    <ul>
      <li><a href="<?php echo $this->data[tracking]; ?>"><?php echo $this->trans->_('text_tracking_affiliate_account'); ?></a></li>
    </ul>
  </div>
  </div>
  

	  	<div class="box">
<div class="box-heading"><p><span><?php echo $this->trans->_('text_my_transactions_affiliate_account'); ?></span></p></div>
<div class="box-content">
    <ul>
      <li><a href="<?php echo $this->data[transaction]; ?>"><?php echo $this->trans->_('text_transaction_affiliate_account'); ?></a></li>
    </ul>
  </div>
    </div>
 </div>
             <!--box end --></div>
			 
			 
	<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>

<!--container End--></div>
<!--main-max-banner End--></div>
