<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?></p>
                 <!--readcrumb End--></div>
				 
                        <div class="page-title">
			 <h1>  <?php echo $this->trans->_('heading_title_affiliate_password'); ?></h1></div>
						
        			
      	<div class="box">     
		
    <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="password">

   
    <h2><?php echo $this->trans->_('text_password_affiliate_password'); ?></h2>
	   <div class="box-content">
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_password_affiliate_password'); ?></td>
          <td><input type="password" name="password" value="<?php echo $this->data[password]; ?>" />
            <?php if ($this->data[error_password]) { ?>
            <span class="error"><?php echo $this->data[error_password]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $this->trans->_('entry_confirm_affiliate_password'); ?></td>
          <td><input type="password" name="confirm" value="<?php echo $this->data[confirm]; ?>" />
            <?php if ($this->data[error_confirm]) { ?>
            <span class="error"><?php echo $this->data[error_confirm]; ?></span>
            <?php } ?></td>
        </tr>
      </table>
    </div>
    
						
						</div>
						<div class="buttons">
      <div class="left"><a href="<?php echo $this->data[back]; ?>" class="button_btn"><span><?php echo $this->trans->_('button_back'); ?></span></a></div>
      <div class="right"><a onclick="$('#password').submit();" class="button_btn"><span><?php echo $this->trans->_('button_submit_affiliate_password'); ?></span></a></div>
    </div>
  </form>
                    <!--box end --></div>
					
								 
	<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
                <!--rightContainer --></div>
            <!--innerContent --></div>