
<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End-->
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

               <div class="breadcrumb"><!--readcrumb start-->
<p>
	<?php foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
    <?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a>
    <?php } ?></p>
                  <!--readcrumb End --></div>
				  
				 <div class="page-title">
<h1><span><?php echo $_SESSION['OBJ']['tr']->translate('heading_title_account_password'); ?></span></h1></div>
     	  
                
				   
                 <div class="box">
				    <div class="box-account-password">   
   <div class="box-content">
    <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="password">
     <div class="content">
	 <h4><?php  echo $_SESSION['OBJ']['tr']->translate('text_password_account_password'); ?></h4>
      <table class="form">
        <tr>
          <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_password_account_password'); ?></td>
          <td><input type="password" name="password" value="<?php echo $this->data[password]; ?>" />
            <?php if ($this->data[error_password]) { ?>
            <span class="error"><?php echo $this->data[error_password]; ?></span>
            <?php } ?></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $_SESSION['OBJ']['tr']->translate('entry_confirm_account_password'); ?></td>
          <td><input type="password" name="confirm" value="<?php echo $this->data[confirm]; ?>" />
            <?php if ($this->data[error_confirm]) { ?>
            <span class="error"><?php echo $this->data[error_confirm]; ?></span>
            <?php } ?></td>
        </tr>
      </table>
    </div>
  </form>
 </div>			
						</div>
						
						
						
              <!--<box end>--></div>
					<div class="buttons">
      <div class="left"><a href="<?php echo $this->data[back]; ?>" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_back'); ?></span></a></div>
      <div class="right"><a onclick="$('#password').submit();" class="button_btn"><span><?php echo $_SESSION['OBJ']['tr']->translate('button_submit_account_password'); ?></span></a></div>
    </div>
<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>                            
<!--container End--></div>
           <!--main-max-banner End--></div>