    <div class="box">
	 <div class="newsletter-div">
	 <div class="modules-box-div">
	   <div class="box-newsletter">
         <div class="box-content">
    <div class="newsletter">
	 <?php if(@constant('newsletter_module_title')!=""){?><h2><?php echo @constant('newsletter_module_title');?></h2><?}?>
	 <p>Add your email address to receive our newsletters.</p>
	 <div class="search">
	<input name="newsletter_email" id="newsletter_email"  type="text" class="search-text" value="News Letter Email"/>
	<div class="search-icon"><a herf="#" class="new-letter-btn"></a></div>
	 </div>
	 </div>
	 
 </div>
			</div>
		</div>
	</div>
</div>