

<div class="box">
	<div class="modules-box-div">
<div class="ratings-div">
<div class="box-heading"><p><span>Ratings</span></p></div>
<div class="box-content">
	<div class="ratings-search">
	<p><a href=""><img src="images/rating-0.png" border="0" /> & <span> upto(0%) </span> </a> </p>
    <p><a href=""><img src="images/rating-1.png" border="0" /> & <span> upto(10%) </span> </a> </p>
    <p><a href=""><img src="images/rating-2.png" border="0" /> & <span> upto(26%) </span> </a> </p>
    <p><a href=""><img src="images/rating-3.png" border="0" /> & <span> upto(44%) </span> </a> </p>
    <p><a href=""><img src="images/rating-4.png" border="0" /> & <span> upto(65%) </span> </a> </p>
	</div>
</div>
</div></div>
</div>