

<div id="container"><!--start container-->

<div class="max-banner">  
<!--max banner js code start-->
<script type="text/javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jquery.pikachoose.js"></script>
<script language="javascript">
$(document).ready(function (){
		$("#pikame").PikaChoose({showTooltips:true});
	});
</script>
<!--max banner js code end-->
<div class="modules-box-div">
<div class="pikachoose">
	<ul id="pikame" >
	  <?foreach($this->info[data][banners] as $k){?>
				<li id="content">
                                    <a href="<?echo $k['link'];?>"><img src="<?php echo $this->url_to_site."timthumb.php?src=".$k['image']; ?>" alt="<?echo $k[title];?>" height="<?echo $this->info[data][height];?>" width="<?echo $this->info[data][width];?>" /></a></li>
				    <?}?>
	</ul>
</div>
<div class="clear"></div>
</div></div>
<div class="clear"></div>
<!--end container--></div>

