	</div> <!-- /.container -->
<footer id="footer">
		<div class="footer_top">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="single_footer_top wow fadeInLeft">
							<h2>Flicker Images</h2>
							<ul class="flicker_nav">
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>                 
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>                 
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
									</li>                 
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>                 
								<li>
									<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="single_footer_top wow fadeInDown">
							<h2>Labels</h2>
							<ul class="labels_nav">
								<li><a href="<?echo $this->url_to_site.'information/information/information_id/1'?>">About Us</a></li>
								<!--<li><a href="<?echo $this->url_to_site.'account/login'?>">Customer Sign In</a></li>
								<li><a href="<?echo $this->url_to_site.'account/register'?>">Customer Register</a></li>
								<li><a href="<?echo $this->url_to_site.'affiliate/login'?>">Affiliate Sign In</a></li>
								<li><a href="<?echo $this->url_to_site.'affiliate/register'?>">Affiliate Register</a></li>-->
							</ul>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="single_footer_top wow fadeInRight">
							<h2><?php echo @constant('STORE_NAME');?></h2>
							<p><?php echo @constant('STORE_NAME_ADDRESS');?></p>
							<p><?php echo @constant('STORE_TELEPHONE');?></p>
							<p><?php echo @constant('STORE_OWNER_EMAIL_ADDRESS');?></p> 
						</div>
					</div>
				</div>
			</div>
		</div>