<div id="container"><!-- container start-->

<div class="footer-div"><!--footer start-->
	<div class="footer-div-box">
		<div class="box">
			<h4>Company</h4>
			<ul class="line-k">
				<li><a href="<?echo $this->url_to_site.'information/information/information_id/1'?>">About Us</a></li>
				<li><a href="<?echo $this->url_to_site.'information/information/information_id/13'?>">Our Promise</a></li>
				<li><a href="<?echo $this->url_to_site.'information/information/information_id/1'?>">Team</a></li>
				<li><a href="<?echo $this->url_to_site.'information/information/information_id/9'?>">Protection</a></li>
				<li><a href="<?echo $this->url_to_site.'information/information/information_id/10'?>">Locations</a></li>
			</ul>
		</div>
	<div class="clear"></div>
	</div>

	<div class="footer-div-box" id="footer-box-2">
	<div class="box" >
	<h4>Buy</h4>
	<ul class="line-k">
				<li><a href="<?echo $this->url_to_site.'product/special'?>">Specials</a></li>
				<li><a href="<?echo $this->url_to_site.'checkout/voucher'?>">Gift Vouchers</a></li>
				<li><a href="<?echo $this->url_to_site.'product/manufacturer'?>">Best Sales Brands</a></li>
				<li><a href=""<?echo $this->url_to_site.'information/information/information_id/12'?>">Security</a></li>
				<li><a href="<?echo $this->url_to_site.'information/contact'?>">Contactus</a></li>


			    </ul>
	</div>
	<div class="clear"></div>
	</div>

<div class="footer-div-box">
<div class="box"  id="footer-box-3">
<h4>Customer</h4>
 <ul class="line-k">
                    	<li><a href="<?echo $this->url_to_site.'account/login'?>">Customer Sign In</a></li>
                        <li><a href="<?echo $this->url_to_site.'account/register'?>">Customer Register</a></li>
                        <li><a href="<?echo $this->url_to_site.'affiliate/login'?>">Affiliate Sign In</a></li>
                        <li><a href="<?echo $this->url_to_site.'affiliate/register'?>">Affiliate Register</a></li>
                        <li><a href="<?echo $this->url_to_site.'information/sitemap'?>">Sitemap</a></li>
                    </ul>
</div>
<div class="clear"></div>
</div>


<div class="footer-div-box" id="footer-box-4" >
<div class="box">
<h4>Contact Us</h4>
<p><?php echo $_SESSION['text']['T_Footer_Contact_Address_Text'];?></p>
<h3><?php echo $_SESSION['text']['T_Footer_Contact_Number_Text'];?></h3>
<div class="pay-icon"><a href="" class="pay-mc-icon"></a> <a href="" class="pay-vise-icon"></a> <a href="" class="pay-ac-icon"></a> <a href="" class="pay-emi-icon"></a> <a href="" class="pay-net-icon"></a>  <a href="" class="pay-cart-icon"></a></div>
</div>
<div class="clear"></div>
</div>
 


<div class="clear"></div>
<!--footer End--></div>
<div class="footer-line-big">

<div class="footer-line-big-inner">
<div class="news-box">
<div class="news-title">Newsletter</div> <div class="news-textbox"><input name="newsletter_email" id="newsletter_email" type="text" value="Enter Email ID" onfocus="value=''" class="new-letter"> <a href="#" class="new-letter-btn"></a></div> </div>
<div class="follow-us-on-box">
<p><span>Follow Us On:</span> <a href="" class="fb-icon"></a> <a href="" class="tw-icon"></a> <a href="" class="rs-icon"></a> <a href="" class="inp-icon"></a> <a href="" class="in-icon"></a></p>
</div>
</div>
</div>

<!--container End--></div>

