<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--<link href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" rel="icon" />-->
<link rel="icon" href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" type="image/x-icon" />
<title><?php echo html_entity_decode($this->meta_title, ENT_QUOTES, 'UTF-8');?></title>

<meta name="description" content="<?php echo html_entity_decode($this->meta_description, ENT_QUOTES, 'UTF-8');?>" />
<meta name="keywords" content="<?php echo html_entity_decode($this->meta_keywords, ENT_QUOTES, 'UTF-8');?>">
<!--Js code start-->

<script type="text/javascript" src="<?php echo $this->url_to_commonfiles;?>js/jquery.js"></script>

<script type="text/javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jquery-ui.min.js"></script>

<?php echo @constant('SITE_JAVASCRIPT_CONSTANTS');?>
<!--popup start  -->
<script type="text/javascript" src="<?php echo $this->url_to_commonfiles;?>js/javascript/jquery/colorbox/jquery.colorbox.js"></script>
<!--popup end  -->
 

<!--Tab Controls Styles & JS files --><!--add to cart js code start-->
<!-- <script type="text/javascript">
var HTTP_SERVER= '<?echo $this->url_to_site;?>';
</script> -->

<script type="text/javascript" src="<?php echo $this->url_to_commonfiles;?>js/javascript/common.js"></script>
<!--end common js  --><!--add to cart js code end-->

<!--Js code End-->

<!--stylesheet code staret-->
<?$main_css_path=file_exists(PATH_TO_FILES."load.css")?$this->url_to_site."public/uploads/".@constant('GLOBAL_DOMAIN_KEY')."/files/load.css":$this->url_to_templates.SITE_DEFAULT_TEMPLATE."/includes/css/load.css";?>
 <!-- <link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/load.css" rel="stylesheet" type="text/css" />
 -->
<link href="<?PHP echo $main_css_path;?>" rel="stylesheet" type="text/css" />
<!-- <link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/load.css" rel="stylesheet" type="text/css" />
 --><link href="<?php echo $this->url_to_commonfiles;?>js/javascript/jquery/ui/themes/ui-lightness/jquery-ui-1.8.9.custom.css" rel="stylesheet" type="text/css" />

<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/jquery.corner.js"></script>
<script type="text/javascript">
		$(document).ready(function(){
			$('.selectyze2').Selectyze({
				theme : 'mac'
			});
		});
	</script>


<!--<script>
$("#menu").corner("");
$("a.button").corner("");
$(".breadcrumb p").corner("");
$("a.button_btn").corner("");
$("#header #cart .heading").corner("");
$("#header #contact .heading").corner("");
$(".box .box-heading").corner("top 8px");
</script>-->

 <script src="<?php echo $this->url_to_commonfiles;?>js/selectyze.jquery.js"></script>
 
 
<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/ie7.css" />
<![endif]-->
<!--[if lt IE 7]>
<link rel="stylesheet" type="text/css" href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/ie6.css" />
<script type="text/javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/DD_belatedPNG_0.0.8a-min.js"></script>
<script type="text/javascript">
DD_belatedPNG.fix('#logo img');
</script>
<![endif]-->

<link rel="stylesheet" type="text/css" href="<?php echo $this->url_to_commonfiles;?>js/javascript/jquery/colorbox/colorbox.css" />



<!--stylesheet code End-->


<!--tabs code End-->
<script type="text/javascript" src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/scripts/tabs.js"></script>

<!--tabs code End-->
<!--start google analytics  -->
<?php echo html_entity_decode(SERVER_GOOGLE_ANALYTICS, ENT_QUOTES, 'UTF-8');?>
<!-- end google analytics -->
</head>

<body>

<div class="main-wraper"> <!-- main-wraper start-->

<div class="main-top-menu-div"><!-- main-top-menu start-->
<div id="container"><!-- container start-->
<div class="top-menu-div">
<!-- top menu start-->
<div class="welcome-div">
<!--<a href="<?php echo HTTP_SERVER;?>" class="home"><span><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/images/home_icon.gif" alt="" border="0"/></span></a>-->
  <?php if (!$this->logged) { ?>
    <?php echo $this->text_welcome_header; ?>
    <?php } else { ?>
    <?php echo $this->text_logged_header; ?>
    <?php } ?>


</ul>
</div>
<?php 
$addon_allcategories="1";
//echo $addon_allcategories=="1"?$this->action('top','modules',null,array('mod' =>$this->pos[top])):"";
//exit;
echo $this->action('addon','addons',null,array('mod' =>'allcategories','params'=>array("hell","well","sell")));?>

 <!--<div class="all-stores-div ">
  <ul><li><a href="" class="all-stores">All</a>
  <div class="style">
  <ul>
  <li><a href="">Shoes</a>
  <div class="style-sub">
  <ul>
   <h3>Men's Shoes</h3>
    <li><a href="">Formal Shoes</a></li>
    <li><a href="">Casual Shoes</a></li>
    <li><a href="">Sports Shoes</a></li>
    <li><a href="">Flip Flops</a></li>
    <li><a href="">Boots</a></li>
    <li><a href="">High Ankle</a></li>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Sale</a></li>
  </ul>
  
   <ul>
   <h3>Women's Shoes</h3>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Flats</a></li>
    <li><a href="">Mid Heels</a></li>
    <li><a href="">High Heels</a></li>
    <li><a href="">Bellys</a></li>
    <li><a href="">Wedges</a></li>
    <li><a href="">Peep Toe</a></li>
  </ul>
  
  <ul>
   <h3>Girl's Shoes</h3>
    <li><a href="">Sports Shoes</a></li>
    <li><a href="">Casual Shoes</a></li>
    <li><a href="">School Shoes</a></li>
    <li><a href="">Bellys</a></li>
    <li><a href="">Flip Flops</a></li>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Sale</a></li>
</ul>
  
  </div>
  </li>
  </ul>
  
  <ul>
   <li><a href="">Clothing</a></li>
   <li><a href="">Bags</a>
     <div class="style-sub">
  <ul>
   <h3>Men's Shoes</h3>
    <li><a href="">Formal Shoes</a></li>
    <li><a href="">Casual Shoes</a></li>
    <li><a href="">Sports Shoes</a></li>
    <li><a href="">Flip Flops</a></li>
    <li><a href="">Boots</a></li>
    <li><a href="">High Ankle</a></li>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Sale</a></li>
  </ul>
  
   <ul>
   <h3>Women's Shoes</h3>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Flats</a></li>
    <li><a href="">Mid Heels</a></li>
    <li><a href="">High Heels</a></li>
    <li><a href="">Bellys</a></li>
    <li><a href="">Wedges</a></li>
    <li><a href="">Peep Toe</a></li>
  </ul>
  
  <ul>
   <h3>Girl's Shoes</h3>
    <li><a href="">Sports Shoes</a></li>
    <li><a href="">Casual Shoes</a></li>
    <li><a href="">School Shoes</a></li>
    <li><a href="">Bellys</a></li>
    <li><a href="">Flip Flops</a></li>
    <li><a href="">All Sandals</a></li>
    <li><a href="">All Slippers</a></li>
    <li><a href="">All Shoes</a></li>
    <li><a href="">Sale</a></li>
</ul>
  
  </div>
   </li>
   <li><a href="">Sarees and Kurtis</a></li>
   <li><a href="">Watches</a></li>
   <li><a href="">Eyewear</a></li>
   <li><a href="">Bath and Beauty</a></li>
   <li><a href="">Jewellery</a></li>
   <li><a href="">Electronics</a></li>
   <li><a href="">Mobile &amp; Tablets</a></li>
  </ul>
  </div>
  
  </li>
  </ul>
  </div> -->

<div class="account-div">
  <ul>
   <li><a href="<?php echo $this->link_account;?>"><span><?php echo $this->trans->_('text_account_common_header');?></span></a></li>
		 <li><a href="<?php echo HTTP_SERVER."account/wishlist"?>" id="wishlist_total" ><span><?php echo $this->wishlistTotal;?></span></a></li>
                <li><a href="<?php echo $this->link_account_order_history?>"><span><?php echo $this->trans->_('text_order_common_footer');?></span></a></li>
                <li><a href="<?php echo HTTP_SERVER."checkout/cart"?>"><span><?php echo $this->trans->_('heading_title_checkout_checkout');?></span></a></li>
  </ul>
</div>
<!-- top menu End-->
</div>
<!-- container End-->
</div>
<!-- main-top-menu End-->
</div>


<div class="main-header-div"> <!-- main-header start-->
  <div id="container"><!-- container start-->

<div class="header-div"><!-- header start-->

      <div class="logo"> <a href="<?php echo HTTP_SERVER;?>"><img src="<?echo PATH_TO_UPLOADS."image/".STORE_LOGO?>"  alt="<?php echo STORE_NAME;?>" /></a></div>
	  
<!--language start--> 
   <?php if(count($_SESSION['Lang']['languages'])>1){?>
      <div id="language">  
       	<form name="frmLang" id="frmLang" method="post" action="">

	<select name="lang" id="lang" class="language"  onchange="document.getElementById('frmLang').submit();">
               <?php
		foreach($_SESSION['Lang']['languages'] as $l)
	       {
		 //$sel=$this->lang->_languageCode==$l[code]?'selected':'';
		 $sel=$_SESSION['Lang']['language_code']==$l[code]?'selected':'';
		 echo "<option value='".$l[code]."' ".$sel." >".$l[name]."</option>";
	       }?>
            </select>

	    </form>
</div>
<?}?>
<!--language End--> 



     <!--currency start-->
     <?php

	if(count($this->curr->currencies)>1){
	?>
      <div class="currency-div"> 
      <form name="frmCurr" id="frmCurr"  method="post" action="">
   
	        <select name="curr" id="curr" class="selectyze2" onchange="document.getElementById('frmCurr').submit();">
               <?php
		foreach($this->curr->currencies as $k=>$v)
	       {
	       	 //$sel=$this->curr->_currency==$k?'selected':'';
		 $sel=$_SESSION['Curr']['currency']==$k?'selected':'';
		 echo "<option value='".$k."' ".$sel." >".$k."</option>";
	       }?>
            </select>
			
	    </form> 
      </div>
      <?}?>
      <!--currency End-->
  <div id="myCart"><!--add to cart start-->
   <div id="cart">
    <div class="heading">
      <h4><?php echo $this->trans->_('text_cart_common_header');?></h4>
      <a><span id="cart_total"><?php echo $this->text_items; ?></span></a></div>
    <div class="content">
	</div>
	
	</div>
   <!--add to cart End-->  </div>

  
  <!-- <form name="frmsearch" id="frmsearch" method="post"> -->
	 <div class="search-div">
	 
    <div class="search-double">
<span> <?
/*echo "<pre>";
print_r($this->catDropDown);
echo "</pre>";*/
?>
	    <select id="dd" name="dd" class="selectyze2" >
              <option value="0"><?php echo $this->trans->_('text_all_categories_common_header');?></option>
              <?php

	      foreach ($this->catDropDown as $category_dropdown) { ?>
              <?php if (trim(str_replace("&nbsp;",'',$category_dropdown['name'])) == $this->dd) { ?>
              <option value="<?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?>" selected="selected"><?php echo $category_dropdown['name']; ?></option>
              <?php } else { ?>
              <option value="<?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?>"><?php echo trim(str_replace("&nbsp;",'',$category_dropdown['name'])); ?></option>
              <?php } ?>
              <?php } ?>
            </select></div>
           
			   

     <div class="search-single">  <input type="text" onblur="if(this.value=='') this.value='<?php echo $this->trans->_('text_search_common_header');?>'" onfocus="if(this.value=='<?php echo $this->trans->_('text_search_common_header');?>') this.value=''" class="search-div-single" value="<?php echo $this->q!=""?$this->q:$this->trans->_('text_search_common_header');?>" id="q" name="q">
		<!-- <input name="q" id="q" type="text"  class="search"   onload="if(this.value==''){value='<?php echo $this->trans->_('text_search_common_header');?>'}else{ value='<?php echo $this->q;?>'}" /> --> <div class="search-button"><a href=""></a></div></div>
</div>
  <!-- </form>
 -->
  
  

  <!-- header End-->   </div>
  <!-- container End--> </div>
<!-- main-header End--></div>

<div class="main-manu-div"><!-- main-menu start-->

<div id="container"><!-- container start-->
<?php
	if ($this->menucategories) { ?>
<div class="manu-div">
<ul class="menu">
 <?php foreach ($this->menucategories as $category) {
       if($category['name']!="")
       {
       ?>
	    <li>
	  <a href="<?php echo $category['href']; ?>" class="first" ><span><?php echo $category['name']; ?></span></a>
	    <?php if ($category['children']) { ?>
<div class="style">
<?php for ($i = 0; $i < count($category['children']);) { ?>
<ul>
<?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
          <?php for (; $i < $j; $i++) { ?>
          <?php if (isset($category['children'][$i])) { ?>
 <li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
          <?php }} ?>

        </ul><?php } ?>

      </div><?php } ?>
	  
	   <?php } }?>
        </li>
		
			<?php }
	if($this->more=='1'){?>
		 <li>
        	<a href="#"><span><?echo $this->trans->_('text_more_common_header');?></span></a>
		 <div class="style">
		 <?php foreach ($this->allCategories as $category) {if($category['top']!="1" && $category['name']!=""){
//foreach ($this->allCategories as $category) {if($category['top']!="1"){ ?>

                    <ul>
                        <li><h2> <a href="<?php echo $category['href']; ?>" class="first" ><?php echo $category['name']; ?></a></h2>
						 <?php if ($category['children']) { ?>
        <?php for ($i = 0; $i < count($category['children']);) { ?>
          <?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
          <?php for (; $i < $j; $i++) { ?>
          <?php if (isset($category['children'][$i])) { ?>
          <li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
          <?php } ?>
          <?php } ?>

        <?php } ?>

      <?php } ?>
                    </ul>

       <?}}?>
      </div>
	  
        </li><?}?>
</ul>

</div>

<!-- container End--> </div>
<!-- main-menu End--></div>


