<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->
<div id="notification"></div>
<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>


<div id="content"><!--content start-->

<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>
<div id="Accordion1" class="Accordion" tabindex="0">
<div class="clear"></div>
</div>
<div class="clear"></div>


			  <div class="footer-model"> <!--footer-model start-->

<div class="box">
<div class="ad-banners-model">
<div class="ad-banner"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/ad-banner-1.png"></div>
<div class="ad-banner"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/ad-banner-2.png"></div>
<div class="ad-banner"><img src="<?php echo $this->url_to_templates.SITE_DEFAULT_TEMPLATE;?>/includes/images/ad-banner-3.png"></div>
</div>
</div>

<!--footer-model end--></div>
              

			  
<!--container End--></div>
<!--main-max-banner End--></div>