<div>
  <div class="cart-heading"><?php echo $this->tr->_('heading_title_total_voucher'); ?></div>
  <div class="cart-content" id="voucher"><?php echo $this->tr->_('entry_voucher_total_voucher'); ?>&nbsp;
    <input type="text" name="voucher" value="<?php echo $this->data[voucher]; ?>" />
    &nbsp;<a id="button-voucher" class="button_btn"><span><?php echo $this->tr->_('button_voucher'); ?></span></a></div>
</div>
<script type="text/javascript"><!--
$('#button-voucher').bind('click', function() {
	$.ajax({
		type: 'POST',
		url: '<?echo HTTP_SERVER;?>order-total/vouchercalculate',
		data: $('#voucher :input'),
		dataType: 'json',
		beforeSend: function() {
			$('.success, .warning').remove();
			$('#button-voucher').attr('disabled', true);
			$('#button-voucher').after('<span class="wait">&nbsp;<img src="<?php echo URL_TO_TEMPLATES.SITE_DEFAULT_TEMPLATE?>/includes/images/loading.gif" alt="" /></span>');
		},
		complete: function() {
			$('#button-voucher').attr('disabled', false);
			$('.wait').remove();
		},
		success: function(json) {
			if (json['error']) {
				$('#basket').before('<div class="warning">' + json['error'] + '<img src="<?php echo URL_TO_TEMPLATES.SITE_DEFAULT_TEMPLATE?>/includes/images/close.png" alt="" class="close" /></div>');
			}

			if (json['redirect']) {
				location = json['redirect'];
			}
		}
	});
});
//--></script>