<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" type="image/x-icon" />
		<link rel="shortcut icon" href="<?echo PATH_TO_UPLOADS."image/".STORE_FAVI_ICON?>" type="image/x-icon" />
		<title><?php echo html_entity_decode($this->meta_title, ENT_QUOTES, 'UTF-8');?></title>
		<meta name="description" content="<?php echo html_entity_decode($this->meta_description, ENT_QUOTES, 'UTF-8');?>" />
		<meta name="keywords" content="<?php echo html_entity_decode($this->meta_keywords, ENT_QUOTES, 'UTF-8');?>">	
		<!-- Bootstrap -->
		<link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/bootstrap.min.css" rel="stylesheet">
		<!-- for fontawesome icon css file -->
		<link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/font-awesome.min.css" rel="stylesheet">
		<!-- for content animate css file -->
		<link rel="stylesheet" href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/animate.css">
		<!-- google fonts  -->
		<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'> 
		<!-- slick slider css file -->
		<link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/slick.css" rel="stylesheet">     
		<!-- <link href="css/theme-red.css" rel="stylesheet"> -->    
		<link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/theme.css" rel="stylesheet">
		<!-- main site css file -->    
		<link href="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/css/style.css" rel="stylesheet">
		
		
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!-- Preloader -->
		<div id="preloader">
			<div id="status">&nbsp;</div>
		</div>
		<!-- End Preloader -->
		
		<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
		
		<div class="container">
			<!-- start header area -->
			<header id="header">
				<div class="row">
					<div class="col-lg-12 col-md-12">
						<!-- start header bottom -->
						<div class="header_bottom">
							<div class="header_bottom_left">
								<!-- for img logo -->
								<!-- <a class="logo" href="index.html">
									<img src="img/logo.jpg" alt="logo">
								</a>-->
								<!-- for text logo -->
								<a class="logo" href="<?php echo HTTP_SERVER;?>"><img src="<?echo PATH_TO_UPLOADS."image/".STORE_LOGO?>"  alt="<?php echo STORE_NAME;?>" width="<?php echo $this->lSize[0];?>" height="<?php echo $this->lSize[1];?>"  /></a>
							</div>
							<div class="header_bottom_right">
								<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/addbanner_728x90_V1.jpg" alt="img"></a>
							</div>
						</div><!-- End header bottom -->
					</div>
				</div>
			</header><!-- End header area -->

			<? if ($this->menucategories) { ?>
			<!-- Static navbar -->
			<div id="navarea">
				<nav class="navbar navbar-default" role="navigation">
					<div class="container-fluid">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>             
						</div>
						
							<div id="navbar" class="navbar-collapse collapse">
								<ul class="nav navbar-nav custom_nav">
									<li class=""><a href="<?php echo HTTP_SERVER;?>">Home</a></li>   
									<?php foreach ($this->menucategories as $category) {
										if($category['name']!="")
										{
										?>
										<li class="dropdown">
											<a href="<?php echo $category['href']; ?>" class="" data-toggle="dropdown" role="button" aria-expanded="false"><?php echo $category['name']; ?></a>
											<?php if ($category['children']) { ?>
												<?php for ($i = 0; $i < count($category['children']);) { ?>
													<ul class="dropdown-menu" role="menu">
														<?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
														<?php for (; $i < $j; $i++) { ?>
															<?php if (isset($category['children'][$i])) { ?>
																<li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
															<?php }} ?>
															
													</ul><?php } } ?>
										</li>            
										
									<? }} ?> 
									<?if($this->more=='1'){?>
										<li class="dropdown">
											<a href="#" class="" data-toggle="dropdown" role="button" aria-expanded="false"><?echo $this->trans->_('text_more_common_header');?></a>
											<?php foreach ($this->allCategories as $category) {if($category['top']!="1" && $category['name']!=""){ ?>
												<ul class="dropdown-menu" role="menu">
													<li><a href="<?php echo $category['href']; ?>" class="first" ><?php echo $category['name']; ?></a>
														<?php if ($category['children']) { ?>
															<?php for ($i = 0; $i < count($category['children']);) { ?>
																<?php $j = $i + ceil(count($category['children']) / $category['column']); ?>
																<?php for (; $i < $j; $i++) { ?>
																	<?php if (isset($category['children'][$i])) { ?>
																		<li><a href="<?php echo $category['children'][$i]['href']; ?>"><?php echo $category['children'][$i]['name']; ?></a></li>
																	<?php } ?>
																<?php } ?>
																
															<?php } ?>
															
														<?php } ?>
													</ul>
													
												<?}}?>
											</li>
										<? } ?>
									</ul>           
								</div><!--/.nav-collapse -->	
						</div><!--/.container-fluid -->
					</nav>
				</div>
				<? } ?>
				<!-- start site main content -->
				<section id="mainContent">        
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="error_page_content">
								<!--<h1>404</h1>-->
								<h2>Site Under Maintanance</h2>
								<h3>We are Making our site more conviniant to present you better</h3>
								<p class="wow fadeInLeftBig">Please, continue to our <a href="index.html">Home page</a></p>
							</div>
						</div>
					</div>
					
				</section><!-- End site main content -->
			</div> <!-- /.container -->
			<footer id="footer">
				<div class="footer_top">
					<div class="container">
						<div class="row">
							<div class="col-lg-4 col-md-4 col-sm-4">
								<div class="single_footer_top wow fadeInLeft">
									<h2>Flicker Images</h2>
									<ul class="flicker_nav">
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>                 
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>                 
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>                 
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>                 
										<li>
											<a href="#"><img src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/img/devhill/75x75.jpg" alt="img"></a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-4">
								<div class="single_footer_top wow fadeInDown">
									<h2>Labels</h2>
									<ul class="labels_nav">
										<li><a href="#">Gallery</a></li>
										<li><a href="#">Business</a></li>
										<li><a href="#">Games</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Sports</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Slider</a></li>
										<li><a href="#">Life & Style</a></li>
									</ul>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-4">
								<div class="single_footer_top wow fadeInRight">
									<h2>About Us</h2>
									<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed nec laoreet orci, eget ullamcorper quam. Phasellus lorem neque, </p>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="footer_bottom">
					<div class="container">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="footer_bottom_left">
									<p>All Rights Reserved <a href="index.html">magExpress</a></p>
								</div>   
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="footer_bottom_right">
									<p>Designed By <a href="http://wpfreeware.com/">WpFreeware</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</footer>
			
			<!-- jQuery google CDN Library -->
			<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/js/jquery.min.js"></script> 
			<!-- For content animatin  -->
			<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/js/wow.min.js"></script>
			<!-- bootstrap js file -->
			<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/js/bootstrap.min.js"></script> 
			<!-- slick slider js file -->
			<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/js/slick.min.js"></script> 
			
			<!-- custom js file include -->
			<script src="<?PHP echo $this->url_to_templates;?><?php echo SITE_DEFAULT_TEMPLATE;?>/includes/js/custom.js"></script> 
			
			<!-- =========================
				//////////////This Theme Design and Developed //////////////////////
			//////////// by www.wpfreeware.com======================-->
			
			
		</body>
	</html>	