<div class="main-column"><!--main-max-banner start-->
<div id="container"><!--container start-->

<? if(count($this->pos[left])>0){?>
<div id="column-left"><!--column-left start-->
<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
<!--column-left End--></div>
<?}?>

<?if(count($this->pos[right])>0){?>
<div id="column-right"><!--column-right start-->
<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
<!--column-right End--></div>
<?}?>
		
            <div id="content"><!--content start-->
<?if(count($this->pos[top])>0){?>
<div id="main-max-banner"><!--start main-max-banner-->
<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
<!--End main-max-banner--></div>
<?}?>

          <div class="breadcrumb"><!--readcrumb start-->
	<p>

                    	<?php    foreach ($this->data[breadcrumbs] as $breadcrumb) { ?>
<?php echo $breadcrumb['separator']; ?><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a> <?php } ?></p>                    <!--readcrumb End --></div>

   

   <?php if ($this->data[success]) { ?>
  <div class="success"><?php echo $this->data[success]; ?></div>
  <?php } ?>
  <?php if ($this->data[error_warning]) { ?>
  <div class="warning"><?php echo $this->data[error_warning]; ?></div>
  <?php } ?>

<!--<div class="page-title">
<h1> <?php echo $this->trans->_('heading_title_affiliate_login'); ?></h1></div>-->

<div class="box">
<div class="affiliate-login-content">

<div class="box-heading" ><p><span> <?php echo $this->trans->_('heading_title_affiliate_login'); ?> </span></p></div>

<div class="box-content">
<div class="login-content" id="login-div-box">
    <p class="register" ><?php echo sprintf($_SESSION['OBJ']['tr']->translate('text_description_affiliate_login'), STORE_NAME, STORE_NAME,AFFLIATE_COMMISSION. '%')
    
    ?></p>
    <div class="left">

      <h2><?php echo $this->trans->_('text_new_affiliate_affiliate_login'); ?></h2>
      <div class="content">
        <p class="para"><?php echo $this->trans->_('text_register_account_affiliate_login'); ?></p>
        <a href="<?php echo $this->data[register]; ?>" class="button_btn"><span><?php echo $this->trans->_('button_create_affiliate'); ?></span></a></div>
    </div>
    <div class="right">
      <h2><?php echo $this->trans->_('text_returning_affiliate_affiliate_login'); ?></h2>
      <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="login">
        <div class="content" id="login-ids">
		
          <p><?php echo $this->trans->_('text_i_am_returning_affiliate_affiliate_login');?></p>
          
		   <div class="from-div-li">
          <div class="name"><?php echo $this->trans->_('entry_email_affiliate_login'); ?></div>
           <div class="email"><input type="text" name="email" value="<?php echo $this->trans->_('entry_email_affiliate_login');?>" onfocus="value=''" /></div>
		   </div>
          
		    <div class="from-div-li">
          <div class="name"><?php echo $this->trans->_('entry_password_affiliate_login'); ?></div>
           <div class="email"><input type="password" name="password" value="<?php echo $this->trans->_('entry_password_affiliate_login');?>" onfocus="value=''" /></div>
		 </div>
		  <div class="from-div-li">
 <div class="name"></div>
          <div class="email">&nbsp;&nbsp;<a href="<?php echo $this->data[forgotten]; ?>"><?php echo $this->trans->_('text_forgotten_affiliate_login'); ?></a></div>
		  </div>
		    <div class="from-div-li">
 <div class="name"></div>
  <div class="email">&nbsp;&nbsp;<a onclick="$('#login').submit();" class="button_btn"><span><?php echo $this->trans->_('button_login'); ?></span></a></div>
  </div>
          <?php if ($this->data[redirect]) { ?>
          <input type="hidden" name="redirect" value="<?php echo $this->data[redirect]; ?>" />
          <?php } ?>
        </div>
      </form>
	    </div>
	  <div id="clear"></div>
    </div><div id="clear"></div>
  </div> <div id="clear"></div>

		    </div>


                  <!--box end --></div>
				<?if(count($this->pos[bottom])>0){?>
<div class="content-bottom"><!--content-bottom srtart-->
<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
</div>
<?}?>

<!--container End--></div>
           <!--main-max-banner End--></div>
<script type="text/javascript">
<!--
$('#login input').keydown(function(e) {
	if (e.keyCode == 13) {
		$('#login').submit();
	}
});
//-->
</script>