<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class="notification n-success"><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						
                    </div>
                    <!-- Table records filtering -->

                </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span> <div class="add-btn-div" ><?php $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?></div> </h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
								  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
                                  <th style="width:20%"><a href="<?php echo $this->actionTitle?>?disType=<?php echo $this->disType?>&sortby=countries_name&page=<?php echo $this->page?>"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"countries_name", "page"=>$_REQUEST['page'] ,"file"=>"countries" ,"label"=>"Country"));?></a></th>
                                  <th style="width:21%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"countries_iso_code_2", "page"=>$_REQUEST['page'] ,"file"=>"countries" ,"label"=>"ISO Code 2"));?></th>
                                  <th style="width:13%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"countries_iso_code_3", "page"=>$_REQUEST['page'] ,"file"=>"countries" ,"label"=>"ISO Code 3"));?></th>
                                  <th style="width:15%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}

							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
                                <td class="<?=$class?>"><?php echo $result['countries_name'];?></td>
                                <td class="<?=$class?>"><?php echo $result['countries_iso_code_2'];?></td>
                                <td class="<?=$class?>"><?php echo $result['countries_iso_code_3'];?></td>
                                <td class="<?=$class?>">

								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result['countries_id'];?>"  />
								<?php
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result['countries_id'],$_REQUEST['page']);
									$act->viewDelB($this->actionTitle,$result['countries_id'],'r_countries','countries_id',$_REQUEST['page']);
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
                             <!-- <div>
                            <span>Apply action to selected:</span>
							<?//$arrmact=array('Pub'=>'Publish','UnPub'=>'UnPublish','Del'=>'Delete');
						$arrmact=array('Del'=>'Delete');
						$act->viewMultipleAction($arrmact);?>

                            </div> -->
       			<?$act->fnmultipleactdropdown(array('Pub'=>'Publish','UnPub'=>'UnPublish','Del'=>'Delete'));?>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}?>
							 <p><b>All fields indicated with * are mandatory</b></p>

                          <div class="mode-box">
<h3><span>Country Details</span></h3>

			 <?  echo $act->field(array('lable'=>'Name','input_title'=>'countries_name','desc'=>'enter first name','input_type'=>'input_text','val'=>$this->data[0]['countries_name'],"req"=>'1'));?>
			  
 <?  echo $act->field(array('lable'=>'Iso Code(2)','input_title'=>'countries_iso_code_2','desc'=>'enter 2 letter ISO country code
','input_type'=>'input_text','val'=>$this->data[0]['countries_iso_code_2'],"req"=>'1','maxlength'=>'maxlength=/"2/"'));?>
				
			   <?  echo $act->field(array('lable'=>'Iso Code(3)','input_title'=>'countries_iso_code_3','desc'=>'enter 3 letter ISO country code
                            ','input_type'=>'input_text','val'=>$this->data[0]['countries_iso_code_3'],"req"=>'1','maxlength'=>'maxlength=/"3/"'));?>
			  </div>
						 </div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>