<?php
	$act=new Model_Adminaction();
 	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class="notification n-success"><?=base64_decode($_REQUEST['msg'])?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						<?php  $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?>
                    </div>
                    <!-- Table records filtering -->


                </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span></h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
								  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
                                  <th style="width:20%">Title</th>
                                  <th style="width:15%"><!--<input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> --><a href="#">Edit</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?

								$rcat=$act->getEditdetails('r_configuration','configuration_key','\'DEFAULT_ORDERS_STATUS_ID\'');
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}
					//echo "<pre>";
					//print_r($this->results);
							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
                                <td class="<?=$class?>"><?php echo $result['title'];?></td>
                                <td class="<?=$class?>">
								<!--input type="checkbox" name="rid[]" id="rid" value="<?php echo $result[$this->r_id];?>"  />-->
								<?php
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result[$this->r_id],$_REQUEST['page']);
									//$act->viewDelB($this->actionTitle,$result[$this->r_id],$this->r_table,$this->r_id,$_REQUEST['page']);
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php
						 if($_REQUEST['type']=='Edit'){
						 echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);
		}					?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?
								if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}
                             	?>
							 <!--<p><b>All fields indicated with * are mandatory<br>
							 </b></p>--><div class="mode-box">
<h3><span>Email Content</span></h3>


                            <?				if($_REQUEST['type']=='Edit')
								$ret=$act->db->fetchAll("select o.*,l.name,l.image,l.code,l.directory from r_email_format o, r_languages l where o.email_format_id='".(int)$_REQUEST['rid']."' and l.languages_id=o.language_id");
								else
								$ret=$act->db->fetchAll("select languages_id as language_id,directory,name,code,image from r_languages");

								if(count($ret)>0)
								{
									$i=0;
									 
									$res=$ret[0];
										$chk=$res['html'];

								echo '<p calss="height-div-s"><i class="title-give">Use given keywords in the email template to replace with database values :</i> <span class="content-d"><b>'.$res['info'].' %store_email% , %store_from_email% , 
%store_logo_path% , %store_customer_login_url% , %store_customer_registration_url% , %store_affiliate_registration_url% , %store_affiliate_login_url% , %store_cart_url% ,  
%store_checkout_url% , %store_name% , %store_url% , %store_owner% , %store_address% , %store_fax% , %store_telephone% </b></span></p>';
 										
								echo '<p><label>Title : </label><span class="content-d">'.$res['title'].'</span></p>';
									
								echo '<p><label>Email Subject</label>';
								echo '<textarea title="Subject" name="subject_'.$res['language_id'].'" id="subject_'.$res['language_id'].'"  cols="100" rows="2">'.$res['subject'].'</textarea></p>';
								
								echo '<p><label>Email Body</label>';
								echo '<textarea title="Email Template" name="email_temp_'.$res['language_id'].'" id="email_temp_'.$res['language_id'].'"   rows="20" cols="120" >'.$res['email_template'].'</textarea></p>';
								}	?>

							 <p><label>Html</label><input type="checkbox" tooltiptext="check if it is html email template" value="1" class="input-medium" id="html" name="html" <?if($chk=="1"){ echo 'checked';}?> ></p>

</div>
						 </div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>

<?if($_REQUEST['rid']!="3"){?>
 <script type="text/javascript" >
window.onload = function()
{
	if(document.getElementById('email_temp_1'))
	{
		var oFCKeditor = new FCKeditor('email_temp_1') ;
		oFCKeditor.BasePath = "<?=PUBLIC_PATH?>js/fckeditor/"; 
		oFCKeditor.Height = 300;
		oFCKeditor.Width = '96%';
		oFCKeditor.ReplaceTextarea() ;
	}
}
</script> 
<?}?>