<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Snopzer</title>
		<link href="<?php echo PATH_TO_ADMIN_CSS;?>login.css" rel="stylesheet" type="text/css" />
	</head>
	<body><div class="wrapper">
		<div class="inner-wrapper">
			<div id="header">
				<h1><a href="<?php echo HTTP_SERVER;?>console"><img src="<?php echo PATH_TO_ADMIN_IMAGES;?>Logo-login.png" border="0" /></a></h1>
			</div>
			<div class="dialog ">
				<div class="dialog-content">
					<h2><img src="<?php echo PATH_TO_ADMIN_IMAGES;?>forgottext.png" /></h2>
					<?if($_REQUEST['msg']!=""){?>
						<div class="errow-box" ><?=base64_decode($_GET['msg']);?> </div>
					<?}?>
					<form name="frmadminlogin" id="frmadminlogin" action="forgot-password" method="post">
						<div class="form-row">
							<div class="form-row-centered">
								<label for="email">Enter your email address for password reset instructions</label>
								<div class="input-wrapper">
									<input type="text" placeholder="" title="Email" class="text " value="" id="email" name="email">
									
								</div>
								<input type="submit" value="Submit" class="button submit" onClick="document.getElementById('frmadminlogin').submit();">
							</div>
						</div>
					</form>
				</div>
				<div class="dialog-footer">
					<div class="dialog-footer-left">
						<p>&copy; 2016 <a href="http://snopzer.com" title="Snopzer" target="_blank"> Snopzer.com </a></p>
					</div>
					<div class="dialog-footer-right">
						<a href="login">Login</a>
					</div>
				</div>			
			</div>
		</div>
	</div>
	</body>
</html>
