<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class="notification n-success"><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						<?php $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?>
                    </div>
                </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span></h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
				  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
				  <th align="center" style="width:2%">Lang_id</th>
                                  <th style="width:20%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"name", "page"=>$_REQUEST['page'] ,"file"=>"language" ,"label"=>"Language Name"));?></th>
                                  <th style="width:21%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"code", "page"=>$_REQUEST['page'] ,"file"=>"language" ,"label"=>"Code"));?></th>
                                  <th style="width:13%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"sort_order", "page"=>$_REQUEST['page'] ,"file"=>"language" ,"label"=>"Sort Order"));?></th>
								  <th style="width:15%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}

							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
				<td align="center" class="<?=$class?>"><?php echo $result['languages_id'];?></td>
                                <td class="<?=$class?>"><a href=""><?php echo $result['name'];?> <?echo trim($result['code'])==DEFAULT_LANGUAGE?'[default]':'';?></a></td>
                                <td class="<?=$class?>"><?php echo $result['code'];?></td>
                                <td class="<?=$class?>"><?php echo $result['sort_order'];?></td>
								<td class="<?=$class?>">
								<?php if($result['languages_id']!='1'){?>
								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result['languages_id'];?>"  /><?}?>
									<?php 
																		$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result['languages_id'],$_REQUEST['page']);
									if($result['languages_id']!='1'){
									$act->viewStatusB($result['status'],'language', $result['languages_id'],'r_languages','status','languages_id',$_REQUEST['page']);

									$act->viewDelB($this->actionTitle,$result['languages_id'],'r_languages','languages_id',$_REQUEST['page']);
									}
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
			    <?$act->fnmultipleactdropdown(array('Pub'=>'Enable','UnPub'=>'Disable','Del'=>'Delete'));?>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}?>
							 <p><b>All fields indicated with * are mandatory</b></p>

 <div class="mode-box">
<h3><span>Language Details</span></h3>
                    <? echo $act->field(array('lable'=>'Name','input_title'=>'name','desc'=>'enter language name','input_type'=>'input_text','val'=>$this->data[0]['name'],"req"=>'1'));?>
		     
			   <? echo $act->field(array('lable'=>'Code','input_title'=>'code','desc'=>'enter language                                                                             code','input_type'=>'input_text','val'=>$this->data[0]['code'],"req"=>'1'));?>
</div><div class="mode-box">
<h3><span>Settings</span></h3>
                  <? echo $act->field(array('lable'=>'Image','input_title'=>'image','desc'=>'enter image                                                                            ','input_type'=>'input_text','val'=>$this->data[0]['image'],"req"=>'1'));?>


                               <? echo $act->field(array('lable'=>'Directory','input_title'=>'directory','desc'=>'enter directory                                                                          ','input_type'=>'input_text','val'=>$this->data[0]['directory'],"req"=>'1'));?>

                   <? echo $act->field(array('lable'=>'Sort order','input_title'=>'sort_order','desc'=>'enter sort_order                                                                         ','input_type'=>'input_text','val'=>$this->data[0]['sort_order'],"req"=>'0'));?>

							<?if($_REQUEST[type]=='Edit'){?>
							<p><label>Set as default</label><input type="checkbox" name="default" id="default" <?echo trim($this->data[0]['code'])==DEFAULT_LANGUAGE?'checked':'';?> value="<?=trim($this->data[0]['code']);?>"></p>
							<p>
							<?}?>
                            <label>Status</label>
							<select name="status" id="status"   class="input-medium"  tooltipText="select status">
							<option value="1" <?echo $status=$this->data[0]['status']=='1'?'selected':'';?>>Enable</option>
							<option value="0" <?echo $status=$this->data[0]['status']=='0'?'selected':'';?> >Disable</option>
							</select>
                           </p>
</div>
						 </div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>