<?php
	$act=new Model_Adminaction();
	$act_ext=new Model_Adminextaction();
	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class='<?php echo $_REQUEST['m']==""?"notification n-success":"notification n-error"?>'><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						
                    </div>
                    <!-- Table records filtering -->
                 </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span> <div class="add-btn-div"><?php $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?></div> </h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                      <?if($this->total_count>0){?>  <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
								  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
                                  <th style="width:60%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"manufacturers_name", "page"=>$_REQUEST['page'] ,"file"=>"manufacturer" ,"label"=>"Manufacturers"));?></th>
			            <th style="width:20%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"sort_order", "page"=>$_REQUEST['page'] ,"file"=>"manufacturer" ,"label"=>"Sort Order"));?></th>
                                  <th style="width:20%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}

							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
                                <td class="<?=$class?>"><?php echo $result['manufacturers_name'];?></td>
				<td class="<?=$class?>"><?php echo $result['sort_order'];?></td>
                                <td class="<?=$class?>">

								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result['manufacturers_id'];?>"  />
								<?php
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result['manufacturers_id'],$_REQUEST['page']);
									$act->viewDelB($this->actionTitle,$result['manufacturers_id'],'r_manufacturers','manufacturers_id',$_REQUEST['page']);
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table><?}else{
							echo "<table id='myTable' class='tablesorter' border='2'><tr><td align='center'>No records to display</td></tr></table>";
							}?>


						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
                             <?$act->fnmultipleactdropdown(array('Del'=>'Delete'));?>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}
								if($_REQUEST['type']=='Edit')
								{
									$ret=$act->getEditdetails('r_manufacturers_info','manufacturers_id',(int)$_REQUEST['rid']);
									foreach($ret as $res)
									{
										$lang[$res['language_id']]=array("manufacturers_url" =>$res['manufacturers_url']);
									}
								}

							//	$act->p($lang,'0');
							 ?>
							 <p><b>All fields indicated with * are mandatory</b></p>
<div class="mode-box">
<h3><span>Manufacturer Details</span></h3>
                            <p>
                                <label>*Manufacturer</label>
                                <input name="name" id="name" type="text" title="Manufacturer Title" class="input-medium" value="<?=$this->data[0]['manufacturers_name'];?>" tooltipText="enter manufacturers title"/>
                           </p>
						   <!-- <p>
                                <label>*Image</label>
                                <input name="image" id="image" title="image" type="file" class="input-medium" value="<?=$this->data[0]['Manufacturers_image'];?>" tooltipText="upload image"/>
                           </p> -->

						   <p>
                                <label>*Image</label>
                                <input name="image" id="image"  type="file" class="input-medium" value="<?=$this->data[0]['manufacturers_image'];?>" tooltipText="upload image"/>
								  <a href="#" style="color:black;cursor:pointer;text-decoration:underline;" class="tt"><?=$this->data[0]['manufacturers_image'];?><span class="tooltip"><img src="<?=PATH_TO_UPLOADS."image/".$this->data[0]['manufacturers_image'];?>"  /></span></a>
						   </p>

                           
						   <input name="prev_image" id="prev_image" type="hidden" value="<?=$this->data[0]['manufacturers_image'];?>" />


						   <?php echo $act->lang_field(array('lable'=>'Manufacturer Description','input_title'=>'manufacturers_url','desc'=>'enter manufacturer description','input_type'=>'textarea','val'=>$lang,"req"=>'0'));

						   echo $act->field(array('lable'=>'Sort Order','input_title'=>'sort_order','desc'=>'enter sort order','input_type'=>'input_text','val'=>$this->data[0]['sort_order'],"req"=>'0'));

						   ?>
						 </div></div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>

<script type="text/javascript" >
				window.onload = function()
				{</script>
				<?$select = $act->db->fetchAll("select * from r_languages order by sort_order");
				foreach($select as $row){?>
				<script type="text/javascript" >
			
					if(document.getElementById('manufacturers_url_<?=$row[languages_id]?>')) 
					{
						var oFCKeditor = new FCKeditor('manufacturers_url_<?=$row[languages_id]?>') ;
					}
						oFCKeditor.BasePath = "<?=PUBLIC_PATH?>js/fckeditor/" ;
						oFCKeditor.Height = 300;
						oFCKeditor.Width = '96%';
						oFCKeditor.ReplaceTextarea() ;
				</script>
				<?}?><script type="text/javascript" >
					}
				</script>

		<?php }?>