<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
?>
<link rel="stylesheet" href="<?=PATH_TO_ADMIN_CSS?>table.css">
<style>
.scrollbox {
    background: none repeat scroll 0 0 #FFFFFF;
    border: 1px solid #CCCCCC;
    height: 100px;
    overflow-y: scroll;
    width: 350px;
}
</style>
<div class="container_12">
      <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
 <form enctype="multipart/form-data" method="post" id="frmEdit" name="frmEdit">
		<div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0"><?php echo $_REQUEST['rid'];?> Details</li>
                         <li class="iconsec">
			<?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
			<li class="iconsec">
			<?php
			if($_REQUEST['type']=='Edit'){
			echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type']);
			}					?></li>
			<li class="iconsec">
			<?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent">
			 			    <?if($_REQUEST[msg]!=""){ echo '<div><span class="notification n-success">'.base64_decode($_REQUEST[msg]).'</span></div> ';}?>
 <!-- <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="form">
 -->

 <table class="form" border="2" id="table-top">
        <tr>
          <td>Product</td>
          <td><input type="text" name="product" value="" /></td>
        </tr>


        <tr>
          <td>&nbsp;</td>
          <td><div class="scrollbox" id="awardwinners-product">
              <?php $class = 'odd'; ?>
              <?php

	      if(sizeof($this->data[products])>0){
	      foreach ($this->data[products] as $product) { ?>
              <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
              <div id="awardwinners-product<?php echo $product['product_id']; ?>" class="<?php echo $class; ?>"><?php echo $product['name']; ?> <img src="<?php echo PATH_TO_ADMIN_IMAGES;?>cross-small.gif" />
                <input type="hidden" value="<?php echo $product['product_id']; ?>" />
              </div>
              <?php }} ?>
            </div>
            <input type="hidden" name="awardwinners_product" value="<?php echo $this->data[awardwinners_product]; ?>" /></td>
        </tr>
      </table>
 <table id="module" class="list">
        <thead>
          <tr>

	    <td class="left"><?php echo 'Image'; ?></td>
	    <td class="left"><?php echo 'Layout'; ?></td>
            <td class="left"><?php echo 'Position'; ?></td>
            <td class="left"><?php echo 'Status'; ?></td>
            <td class="right"><?php echo 'Sort Order'; ?></td>
            <td></td>
          </tr>
        </thead>
        <?php
	$module_row = 0; ?>
        <?php foreach ($this->data[modules] as $module) { ?>
        <tbody id="module-row<?php echo $module_row; ?>">
          <tr>

		<td class="left"><input type="text" name="awardwinners_<?php echo $module_row; ?>_image_width" value="<?php echo $this->data['awardwinners_' . $module . '_image_width']; ?>" size="3" />
		<input type="text" name="awardwinners_<?php echo $module_row; ?>_image_height" value="<?php echo $this->data['awardwinners_' . $module . '_image_height']; ?>" size="3" />
		</td>

            <td class="left"><select name="awardwinners_<?php echo $module_row; ?>_layout_id">
                <?php foreach ($this->data[layouts] as $layout) { ?>
                <?php if ($layout['layout_id'] == $this->data['awardwinners_' . $module . '_layout_id']) { ?>
                <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></td>

	    <td class="left">
	    <select name="awardwinners_<?php echo $module_row; ?>_position">
                <?php if ($this->data['awardwinners_' . $module . '_position'] == 'top') { ?>
                <option value="top" selected="selected"><?php echo 'Top'; ?></option>
                <?php } else { ?>
                <option value="top"><?php echo 'Top'; ?></option>
                <?php } ?>
                <?php if ($this->data['awardwinners_' . $module . '_position'] == 'bottom') { ?>
                <option value="bottom" selected="selected"><?php echo 'Bottom'; ?></option>
                <?php } else { ?>
                <option value="bottom"><?php echo 'Bottom'; ?></option>
                <?php } ?>
                <?php if ($this->data['awardwinners_' . $module . '_position'] == 'left') { ?>
                <option value="left" selected="selected"><?php echo 'Left'; ?></option>
                <?php } else { ?>
                <option value="left"><?php echo 'Left'; ?></option>
                <?php } ?>
                <?php if ($this->data['awardwinners_' . $module . '_position'] == 'right') { ?>
                <option value="right" selected="selected"><?php echo 'Right'; ?></option>
                <?php } else { ?>
                <option value="right"><?php echo 'Right'; ?></option>
                <?php } ?>
               </select></td>
            <td class="left"><select name="awardwinners_<?php echo $module_row; ?>_status">
                <?php if ($this->data['awardwinners_' . $module . '_status']) { ?>
                <option value="1" selected="selected"><?php echo 'Enable'; ?></option>
                <option value="0"><?php echo 'Disable'; ?></option>
                <?php } else { ?>
                <option value="1"><?php echo 'Enable'; ?></option>
                <option value="0" selected="selected"><?php echo 'Disable'; ?></option>
                <?php } ?>
              </select></td>
            <td class="right"><input type="text" name="awardwinners_<?php echo $module_row; ?>_sort_order" value="<?php echo $this->data['awardwinners_' . $module . '_sort_order']; ?>" size="3" /></td>
            <td class="left"><a onclick="$('#module-row<?php echo $module_row; ?>').remove();" class="button"><span><?php echo 'Remove'; ?></span></a></td>
          </tr>
        </tbody>
        <?php $module_row++; ?>
        <?php } ?>
        <tfoot>
          <tr>
            <td colspan="5"></td>
            <td class="left"><a onclick="addModule();" class="button"><span><?php echo 'Add Module'; ?></span></a></td>
          </tr>
        </tfoot>
      </table>
      <input type="hidden" name="awardwinners_module" value="<?php echo $this->data['awardwinners_module']; ?>" />

			 </div>
                    </div>
                  </div>
                     <div class="module-body">
                  </div>
                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
</form>
<script type="text/javascript" src="<?php echo URL_TO_TEMPLATES;?>javascript/jquery/jquery-1.6.1.min.js"></script>
<script type="text/javascript" src="<?php echo URL_TO_TEMPLATES;?>javascript/jquery/ui/jquery-ui-1.8.9.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo URL_TO_TEMPLATES;?>javascript/jquery/ui/themes/ui-lightness/jquery-ui-1.8.9.custom.css" />
<script type="text/javascript"><!--
$('input[name=\'product\']').autocomplete({
	delay: 0,
	source: function(request, response) {
		$.ajax({
			url: 'productautocomplete?token=<?echo rand(10,100);?>',
			type: 'POST',
			dataType: 'json',
			data: 'filter_name=' +  encodeURIComponent(request.term),
			success: function(data) {
				response($.map(data, function(item) {
					return {
						label: item.name,
						value: item.product_id
					}
				}));

			}
		});

	},
	select: function(event, ui) {
		$('#awardwinners-product' + ui.item.value).remove();

		$('#awardwinners-product').append('<div id="awardwinners-product' + ui.item.value + '">' + ui.item.label + '<img src="<?php echo PATH_TO_ADMIN_IMAGES;?>cross-small.gif" /><input type="hidden" value="' + ui.item.value + '" /></div>');

		$('#awardwinners-product div:odd').attr('class', 'odd');
		$('#awardwinners-product div:even').attr('class', 'even');
				//fnfprod();


		return false;
	}
});

$('#awardwinners-product div img').live('click', function() {
		//fnfprod();

	$(this).parent().remove();

	$('#awardwinners-product div:odd').attr('class', 'odd');
	$('#awardwinners-product div:even').attr('class', 'even');
});
//--></script>

<script type="text/javascript"><!--
var module_row = <?php echo $module_row; ?>;

function addModule() {
	html  = '<tbody id="module-row' + module_row + '">';
	html += '  <tr>';
	html += '    <td class="left"><input type="text" name="awardwinners_' + module_row + '_image_width" value="" size="3" /> <input type="text" name="awardwinners_' + module_row + '_image_height" value="" size="3" /></td>';
	html += '    <td class="left"><select name="awardwinners_' + module_row + '_layout_id">';
	<?php foreach ($this->data[layouts] as $layout) { ?>
	html += '      <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>';
	<?php } ?>
	html += '    </select></td>';
	html += '    <td class="left"><select name="awardwinners_' + module_row + '_position">';
	html += '      <option value="top">Top</option>';
	html += '      <option value="bottom">Bottom</option>';
	html += '      <option value="left">Left</option>';
	html += '      <option value="right">Right</option>';
	html += '    </select></td>';
	html += '    <td class="left"><select name="awardwinners_' + module_row + '_status">';
    html += '      <option value="1" selected="selected"><?php echo "Enable"; ?></option>';
    html += '      <option value="0"><?php echo "Disable"; ?></option>';
    html += '    </select></td>';
	html += '    <td class="right"><input type="text" name="awardwinners_' + module_row + '_sort_order" value="" size="3" /></td>';
	html += '    <td class="left"><a onclick="$(\'#module-row' + module_row + '\').remove();" class="button"><span><?php echo "Remove"; ?></span></a></td>';
	html += '  </tr>';
	html += '</tbody>';

	$('#module tfoot').before(html);

	module_row++;
}


$('#frmEdit').bind('click', function() {
	 data = $.map($('#awardwinners-product input'), function(element){
		return $(element).attr('value');
	});
	$('input[name=\'awardwinners_product\']').attr('value', data.join());
//alert(data);

	var module = new Array();

	$('#module tbody').each(function(index, element) {
		module[index] = $(element).attr('id').substr(10);
	});

	$('input[name=\'awardwinners_module\']').attr('value', module.join(','));
});

/*function fnfprod()
{
data = $.map($('#awardwinners-product input'), function(element){
		return $(element).attr('value');
	});
	$('input[name=\'awardwinners_product\']').attr('value', data.join());
alert(data);
}*/
//-->


</script>