<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
?>
<div class="container_12">
      <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0"><?php echo $_REQUEST['rid'];?> Details</li>
                         <li class="iconsec">
			<?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
			<li class="iconsec">
			<?php
			if($_REQUEST['type']=='Edit'){
			echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type']);
			}					?></li>
			<li class="iconsec">
			<?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent">
			 			    <?if($_REQUEST[msg]!=""){ echo '<div><span class="notification n-success">'.base64_decode($_REQUEST[msg]).'</span></div> ';}?>
 <!-- <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="form">
 -->
 <form enctype="multipart/form-data" method="post" id="frmEdit" name="frmEdit">
 <table id="module" class="list">
        <thead>
          <tr>
            <td class="left"><?php echo 'Banner'; ?></td>
	    <td class="left"><?php echo 'Dimension(W*H)'; ?></td>
	    <td class="left"><?php echo 'Layout'; ?></td>
            <td class="left"><?php echo 'Position'; ?></td>
            <td class="left"><?php echo 'Status'; ?></td>
            <td class="right"><?php echo 'Sort Order'; ?></td>
            <td></td>
          </tr>
        </thead>
        <?php
	/*echo "<pre>";
	//echo $this->data->slideshow_modules;
	$arr=$this->data;
	echo $arr[slideshow_module];
	//print_r($this->data);
	echo $this->data['slideshow_module'];
	echo "</pre>";*/

	$module_row = 0; ?>
        <?php foreach ($this->data[modules] as $module) { ?>
        <tbody id="module-row<?php echo $module_row; ?>">
          <tr>
		  <td class="left"><select name="slideshow_<?php echo $module_row; ?>_banner_id">
                <?php foreach ($this->data[banners] as $banner) { ?>
                <?php if ($banner['banner_id'] == @constant('slideshow_' . $module . '_banner_id')) { ?>
                <option value="<?php echo $banner['banner_id']; ?>" selected="selected"><?php echo $banner['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $banner['banner_id']; ?>"><?php echo $banner['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></td>


		<td class="left"><input type="text" name="slideshow_<?php echo $module_row; ?>_width" value="<?php echo $this->data['slideshow_' . $module . '_width']; ?>" size="3" />
		<input type="text" name="slideshow_<?php echo $module_row; ?>_height" value="<?php echo $this->data['slideshow_' . $module . '_height']; ?>" size="3" />
		</td>

            <td class="left"><select name="slideshow_<?php echo $module_row; ?>_layout_id">
                <?php foreach ($this->data[layouts] as $layout) { ?>
                <?php if ($layout['layout_id'] == $this->data['slideshow_' . $module . '_layout_id']) { ?>
                <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></td>

	    <td class="left lease">
	    <select name="slideshow_<?php echo $module_row; ?>_position">
                <?php if ($this->data['slideshow_' . $module . '_position'] == 'top') { ?>
                <option value="top" selected="selected"><?php echo 'Top'; ?></option>
                <?php } else { ?>
                <option value="top"><?php echo 'Top'; ?></option>
                <?php } ?>
                <?php if ($this->data['slideshow_' . $module . '_position'] == 'bottom') { ?>
                <option value="bottom" selected="selected"><?php echo 'Bottom'; ?></option>
                <?php } else { ?>
                <option value="bottom"><?php echo 'Bottom'; ?></option>
                <?php } ?>
                <?php if ($this->data['slideshow_' . $module . '_position'] == 'left') { ?>
                <option value="left" selected="selected"><?php echo 'Left'; ?></option>
                <?php } else { ?>
                <option value="left"><?php echo 'Left'; ?></option>
                <?php } ?>
                <?php if ($this->data['slideshow_' . $module . '_position'] == 'right') { ?>
                <option value="right" selected="selected"><?php echo 'Right'; ?></option>
                <?php } else { ?>
                <option value="right"><?php echo 'Right'; ?></option>
                <?php } ?>
               </select></td>
            <td class="left lease"><select name="slideshow_<?php echo $module_row; ?>_status">
                <?php if ($this->data['slideshow_' . $module . '_status']) { ?>
                <option value="1" selected="selected"><?php echo 'Enable'; ?></option>
                <option value="0"><?php echo 'Disable'; ?></option>
                <?php } else { ?>
                <option value="1"><?php echo 'Enable'; ?></option>
                <option value="0" selected="selected"><?php echo 'Disable'; ?></option>
                <?php } ?>
              </select></td>
            <td class="right"><input type="text" name="slideshow_<?php echo $module_row; ?>_sort_order" value="<?php echo $this->data['slideshow_' . $module . '_sort_order']; ?>" size="3" /></td>
            <td class="left"><a onclick="$('#module-row<?php echo $module_row; ?>').remove();" class="button"><span><?php echo 'Remove'; ?></span></a></td>
          </tr>
        </tbody>
        <?php $module_row++; ?>
        <?php } ?>
        <tfoot>
          <tr>
            <td colspan="6"></td>
            <td class="left"><a onclick="addModule();" class="button"><span><?php echo 'Add Module'; ?></span></a></td>
          </tr>
        </tfoot>
      </table>
      <input type="hidden" name="slideshow_module" value="<?php echo $this->data['slideshow_module']; ?>" />
    </form>
			 </div>
                    </div>
                  </div>
                     <div class="module-body">
                  </div>
                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
<script type="text/javascript"><!--
var module_row = <?php echo $module_row; ?>;

function addModule() {
	html  = '<tbody id="module-row' + module_row + '">';
	html += '  <tr>';
	html += '    <td class="left"><select name="slideshow_' + module_row + '_banner_id">';
	<?php foreach ($this->data[banners] as $banner) { ?>
	html += '      <option value="<?php echo $banner['banner_id']; ?>"><?php echo $banner['name']; ?></option>';
	<?php } ?>
	html += '    </select></td>';
	html += '    <td class="left"><input type="text" name="slideshow_' + module_row + '_width" value="" size="3" /> <input type="text" name="slideshow_' + module_row + '_height" value="" size="3" /></td>';
	html += '    <td class="left"><select name="slideshow_' + module_row + '_layout_id">';
	<?php foreach ($this->data[layouts] as $layout) { ?>
	html += '      <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>';
	<?php } ?>
	html += '    </select></td>';
	html += '    <td class="left"><select name="slideshow_' + module_row + '_position">';
	html += '      <option value="top">Top</option>';
	html += '      <option value="bottom">Bottom</option>';
	html += '      <option value="left">Left</option>';
	html += '      <option value="right">Right</option>';
	html += '    </select></td>';
	html += '    <td class="left"><select name="slideshow_' + module_row + '_status">';
	html += '      <option value="1" selected="selected"><?php echo "Enable"; ?></option>';
	html += '      <option value="0"><?php echo "Disable"; ?></option>';
	html += '    </select></td>';
	html += '    <td class="right"><input type="text" name="slideshow_' + module_row + '_sort_order" value="" size="3" /></td>';
	html += '    <td class="left"><a onclick="$(\'#module-row' + module_row + '\').remove();" class="button"><span><?php echo "Remove"; ?></span></a></td>';
	html += '  </tr>';
	html += '</tbody>';

	$('#module tfoot').before(html);

	module_row++;
}

$('#frmEdit').bind('click', function() {
 	var module = new Array();

	$('#module tbody').each(function(index, element) {
		module[index] = $(element).attr('id').substr(10);
	});

	$('input[name=\'slideshow_module\']').attr('value', module.join(','));
	//fnSave(<?=$url?>);
});
//--></script>