<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
$prefix="facebookconnect";
?>
<div class="container_12">
      <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0"><?php echo $_REQUEST['rid'];?> Details</li>
                         <li class="iconsec">
			<?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
			<li class="iconsec">
			<?php
			if($_REQUEST['type']=='Edit'){
			echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type']);
			}					?></li>
			<li class="iconsec">
			<?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent">
			 			    <?if($_REQUEST[msg]!=""){ echo '<div><span class="notification n-success">'.base64_decode($_REQUEST[msg]).'</span></div> ';}?>
 <!-- <form action="<?php echo $this->data[action]; ?>" method="post" enctype="multipart/form-data" id="form">
 -->
 <form enctype="multipart/form-data" method="post" id="frmEdit" name="frmEdit">
 <table class="form">
	      	<tbody><tr>
          <td><span class="required">*</span> Facebook API Key:</td>
          <td><input type="text" value="<?php echo $this->data[$prefix.'_apikey'];?>" size="50" id="<?php echo $prefix;?>_apikey" name="<?php echo $prefix;?>_apikey"> </td>
	</tr>
      	<tr>
          <td><span class="required">*</span> Facebook API Secret:</td>
          <td><input type="text" value="<?php echo $this->data[$prefix.'_apisecret'];?>" size="50" id="<?php echo $prefix;?>_apisecret" name="<?php echo $prefix;?>_apisecret"> </td>
	</tr>

	<tr>
	<td>Connect Button:</td>
	 <td>
	 <textarea rows="3" cols="50" id="<?php echo $prefix;?>_button" name="<?php echo $prefix;?>_button"><?php echo $this->data[$prefix.'_button'];?></textarea>
	 <span class="help">Can be text or html code.</span>
     	  </td>
	</tr>
	      </tbody></table>
 <table id="module" class="list">
        <thead>
          <tr>
	    <td class="left"><?php echo 'Layout'; ?></td>
            <td class="left"><?php echo 'Position'; ?></td>
            <td class="left"><?php echo 'Status'; ?></td>
            <td class="right"><?php echo 'Sort Order'; ?></td>
            <td></td>
          </tr>
        </thead>
        <?php
	$module_row = 0; ?>
        <?php foreach ($this->data[modules] as $module) { ?>
        <tbody id="module-row<?php echo $module_row; ?>">
          <tr>
          
            <td class="left"><select name="<?php echo $prefix?>_<?php echo $module_row; ?>_layout_id">
                <?php foreach ($this->data[layouts] as $layout) { ?>
                <?php if ($layout['layout_id'] == $this->data[$prefix.'_' . $module . '_layout_id']) { ?>
                <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                <?php } else { ?>
                <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                <?php } ?>
                <?php } ?>
              </select></td>

	    <td class="left">
	    <select name="<?php echo $prefix;?>_<?php echo $module_row; ?>_position">
                <?php if ($this->data[$prefix.'_' . $module . '_position'] == 'top') { ?>
                <option value="top" selected="selected"><?php echo 'Top'; ?></option>
                <?php } else { ?>
                <option value="top"><?php echo 'Top'; ?></option>
                <?php } ?>
                <?php if ($this->data[$prefix.'_' . $module . '_position'] == 'bottom') { ?>
                <option value="bottom" selected="selected"><?php echo 'Bottom'; ?></option>
                <?php } else { ?>
                <option value="bottom"><?php echo 'Bottom'; ?></option>
                <?php } ?>
                <?php if ($this->data[$prefix.'_' . $module . '_position'] == 'left') { ?>
                <option value="left" selected="selected"><?php echo 'Left'; ?></option>
                <?php } else { ?>
                <option value="left"><?php echo 'Left'; ?></option>
                <?php } ?>
                <?php if ($this->data[$prefix.'_' . $module . '_position'] == 'right') { ?>
                <option value="right" selected="selected"><?php echo 'Right'; ?></option>
                <?php } else { ?>
                <option value="right"><?php echo 'Right'; ?></option>
                <?php } ?>
               </select></td>
            <td class="left"><select name="<?php echo $prefix;?>_<?php echo $module_row; ?>_status">
                <?php if ($this->data[$prefix.'_' . $module . '_status']) { ?>
                <option value="1" selected="selected"><?php echo 'Enable'; ?></option>
                <option value="0"><?php echo 'Disable'; ?></option>
                <?php } else { ?>
                <option value="1"><?php echo 'Enable'; ?></option>
                <option value="0" selected="selected"><?php echo 'Disable'; ?></option>
                <?php } ?>
              </select></td>
            <td class="right"><input type="text" name="<?php echo $prefix;?>_<?php echo $module_row; ?>_sort_order" value="<?php echo $this->data[$prefix.'_' . $module . '_sort_order']; ?>" size="3" /></td>
            <td class="left"><a onclick="$('#module-row<?php echo $module_row; ?>').remove();" class="button"><span><?php echo 'Remove'; ?></span></a></td>
          </tr>
        </tbody>
        <?php $module_row++; ?>
        <?php } ?>
        <tfoot>
          <tr>
            <td colspan="4"></td>
            <td class="left"><a onclick="addModule();" class="button"><span><?php echo 'Add Module'; ?></span></a></td>
          </tr>
        </tfoot>
      </table>
      <input type="hidden" name="<?php echo $prefix;?>_module" value="<?php echo $this->data[$prefix.'_module']; ?>" />
    </form>
			 </div>
                    </div>
                  </div>
                     <div class="module-body">
                  </div>
                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
<script type="text/javascript"><!--
var module_row = <?php echo $module_row; ?>;
var prefix="facebookconnect";
function addModule() {
	html  = '<tbody id="module-row' + module_row + '">';
	html += '  <tr>';
	html += '    <td class="left"><select name="'+prefix+'_' + module_row + '_layout_id">';
	<?php foreach ($this->data[layouts] as $layout) { ?>
	html += '      <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>';
	<?php } ?>
	html += '    </select></td>';
	html += '    <td class="left"><select name="'+prefix+'_' + module_row + '_position">';
	html += '      <option value="top">Top</option>';
	html += '      <option value="bottom">Bottom</option>';
	html += '      <option value="left">Left</option>';
	html += '      <option value="right">Right</option>';
	html += '    </select></td>';
	html += '    <td class="left"><select name="'+prefix+'_' + module_row + '_status">';
	html += '      <option value="1" selected="selected"><?php echo "Enable"; ?></option>';
	html += '      <option value="0"><?php echo "Disable"; ?></option>';
	html += '    </select></td>';
	html += '    <td class="right"><input type="text" name="'+prefix+'_' + module_row + '_sort_order" value="" size="3" /></td>';
	html += '    <td class="left"><a onclick="$(\'#module-row' + module_row + '\').remove();" class="button"><span><?php echo "Remove"; ?></span></a></td>';
	html += '  </tr>';
	html += '</tbody>';

	$('#module tfoot').before(html);

	module_row++;
}

$('#frmEdit').bind('click', function() {
 	var module = new Array();

	$('#module tbody').each(function(index, element) {
		module[index] = $(element).attr('id').substr(10);
	});

	$('input[name=\''+prefix+'_module\']').attr('value', module.join(','));
	//fnSave(<?=$url?>);
});
//--></script>