<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
 	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class='<?php echo $_REQUEST['m']==""?"notification n-success":"notification n-error"?>'><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
					
                    </div>
                    <!-- Table records filtering -->


                </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span> <div class="add-btn-div"><?php  $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?></div> </h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
								  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
                                  <th style="width:20%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"orders_status_name", "page"=>$_REQUEST['page'] ,"file"=>"order-status" ,"label"=>"Order Status"));?></th>
                                  <th style="width:15%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?

								$rcat=$act->getEditdetails('r_configuration','configuration_key','\'DEFAULT_ORDERS_STATUS_ID\'');
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}
					//echo "<pre>";
					//print_r($this->results);
							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
                                <td class="<?=$class?>"><?php echo $result['orders_status_name']; if($rcat[0]['configuration_value']==$result['orders_status_id']){ echo "   [default]";}?></td>
			         <td class="<?=$class?>">
								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result[$this->r_id];?>"  />
								<?php
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result[$this->r_id],$_REQUEST['page']);
									$act->viewDelB($this->actionTitle,$result[$this->r_id],$this->r_table,$this->r_id,$_REQUEST['page']);
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">

			     <?$act->fnmultipleactdropdown(array('Del'=>'Delete'));?>
			     <i>Note:Need at least one order status with default status to proceed orders.</i>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php
						 if($_REQUEST['type']=='Edit'){
						 echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);
		}					?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?
								if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}
                             	?>
				<div class="mode-box">
<h3><span>Order Status Details</span></h3>
							 <p><b>All fields indicated with * are mandatory<br>

							 Note:your can use these keywords[ %customer_name% , %order_id% , %order_status% , %comments% ] in your email template to replace with original content</b></p>
                            <?
								$rcat=$act->getEditdetails('r_configuration','configuration_key','\'DEFAULT_ORDERS_STATUS_ID\'');
								//echo "value of ".$rcat[0]['configuration_value'];

								if($_REQUEST['type']=='Edit')
								$ret=$act->db->fetchAll("select o.*,l.name,l.image,l.code,l.directory from r_orders_status o, r_languages l where o.orders_status_id='".(int)$_REQUEST['rid']."' and l.languages_id=o.language_id");
								else
								$ret=$act->db->fetchAll("select languages_id as language_id,name,code,image,directory from r_languages");

								if(count($ret)>0)
								{
									$i=0;
									foreach($ret as $res)
									{
										$chk=$res['html'];
										echo '<p>';

										echo '<label>*Orders Status</label>';
										echo '<input type="text" name="orders_status_name_'.$res['language_id'].'" id="orders_status_name_'.$res['language_id'].'" class="input-medium" tooltipText="order status title" value="'.$res['orders_status_name'].'"  title="Title" ></p>';
										echo '<p>';

										echo '<label>Email Subject</label>';
									 	echo '<textarea name="subject_'.$res['language_id'].'" id="subject_'.$res['language_id'].'" rows="2" cols="100"  >'.$res['subject'].'</textarea></p>';

										echo '<p><label>Email Body</label>';
									 	echo '<textarea name="email_temp_'.$res['language_id'].'" id="email_temp_'.$res['language_id'].'"   cols="100" rows="8" >'.$res['email_template'].'</textarea></p>';

									$i++;}
								}
										$chk3=$rcat[0]['configuration_value']==(int)$_REQUEST['rid']?'checked':'';
										echo '<p><label>Set as Default</label> <input type="checkbox" name="default" id="default" '.$chk3.' tooltipText="Set as Default" value="'.(int)$_REQUEST['rid'].'" ></p>';
								?>
<p><label>Html</label><input type="checkbox" tooltiptext="check if it is html email template" value="1" class="input-medium" id="html" name="html" <?if($chk=="1"){ echo 'checked';}?> ></p>


</div>
						 </div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>

