<?php
	$act=new Model_Adminaction();
	$act_ext=new Model_Adminextaction();
 	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class="notification n-success"><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>
				
                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						
                    </div>
                    <!-- Table records filtering -->
                    
                    
                </div>
                
                
                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span> <div class="add-btn-div"><?php $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?></div> </h2>
                    
                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>"> 
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
								  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
                                  <th style="width:20%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"p.products_name", "page"=>$_REQUEST['page'] ,"file"=>"review" ,"label"=>"Product"));?></th>
								  <th style="width:15%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"r.customers_name", "page"=>$_REQUEST['page'] ,"file"=>"review" ,"label"=>"Author"));?></th>
								  <th style="width:15%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"r.reviews_rating", "page"=>$_REQUEST['page'] ,"file"=>"review" ,"label"=>"Rating"));?></th>
								   <th style="width:15%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"r.date_added", "page"=>$_REQUEST['page'] ,"file"=>"review" ,"label"=>"Date Added"));?></th>
								   <th style="width:15%"><?echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"r.reviews_status", "page"=>$_REQUEST['page'] ,"file"=>"review" ,"label"=>"Status"));?></th>
                                  <th style="width:15%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>
						
							<? 
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}

							foreach ($this->results as $result) 
							{
							 
							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
                                 <td class="<?=$class?>"><?php echo $result['products_name'];?></td>
								 <td class="<?=$class?>"><?php echo $result['customers_name'];?></td>
								 <td class="<?=$class?>"><?php echo $result['reviews_rating'];?></td>
								 <td class="<?=$class?>"><?php echo $result['date_added'];?></td>
								 <td class="<?=$class?>"><?php echo $result['reviews_status']=='1'?'Enable':'Disable';?></td>
                                <td class="<?=$class?>">
                                
								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result[$this->r_id];?>"  />
								<?php 
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result[$this->r_id],$_REQUEST['page']);
									$act->viewDelB($this->actionTitle,$result[$this->r_id],$this->r_table,$this->r_id,$_REQUEST['page']);
								?>	
								
                                </td>
                              </tr>
                              <?$i=$i+1;}?>
                                 
                            </tbody>
                        </table>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
                             <?$act->fnmultipleactdropdown(array('Del'=>'Delete',"Approve"=>"Enable"));?>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>  
                </div>  

                <?=$this->view_pagination;?>
			</div>  
             <div class="grid_6">
		  </div>  
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>  
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){ 
 	/*foreach ($this->data as $result) 
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
			<?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
			<?php echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);?> 
			<li class="iconsec">
			<?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul> 
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}?>
							 <p><b>All fields indicated with * are mandatory</b></p>
							 <div class="mode-box">
<h3><span>Review Details</span></h3>
							<?
							echo $act->field(array('lable'=>'Customer Name','input_title'=>'name','desc'=>'','input_type'=>'input_text','val'=>$this->data[0]['customers_name'],"req"=>'0','readonly'=>'readonly'));

							echo $act->field(array('lable'=>'Product','input_title'=>'product','desc'=>'name of the product','input_type'=>'input_text','val'=>$this->data[0]['products_name'],"req"=>'0','readonly'=>'readonly'));

							echo $act->field(array('lable'=>'Review','input_title'=>'text','desc'=>'review ','input_type'=>'textarea','val'=>$this->data[0]['reviews_text'],"req"=>'0'));
							?>
							<p>

							<label>Rating</label>
							<span class="leade">
							Bad <input type="radio" value="1" class="redio-icon" name="rating" <?echo $this->data[0]['reviews_rating']=='1'?'checked':'';?> >
								<input type="radio" value="2" class="redio-icon" name="rating" <?echo $this->data[0]['reviews_rating']=='2'?'checked':'';?> >
								<input type="radio" value="3" class="redio-icon" name="rating" <?echo $this->data[0]['reviews_rating']=='3'?'checked':'';?> >
								<input type="radio" value="4" class="redio-icon" name="rating" <?echo $this->data[0]['reviews_rating']=='4'?'checked':'';?> >
								<input type="radio" value="5" class="redio-icon" name="rating" <?echo $this->data[0]['reviews_rating']=='5'?'checked':'';?> > Good </span>
							</p>
							<?

							echo $act->field(array('lable'=>'status','input_title'=>'status','desc'=>'enable or disable review','input_type'=>'select','val'=>$act->reviewstatusdropdown($this->data[0]['reviews_status']),"req"=>'0'));
							?>
							</div>
						    
						 </div>
                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div> 

                </div>  
        		<div style="clear:both;"></div>
            </div> 
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>