<?php
	$act=new Model_Adminaction();
	$act_ext=new Model_Adminextaction();
	$currency=new Model_currencies();
 	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;" ></div>
            <div class="grid_12" >


				<?if($_REQUEST['msg']!=""){?>
				<span class="notification n-error"><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right">
		    <?=$this->view_pagination;?>
						<?php //$act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);
						//print_r($this->data);
						?>
                    </div>
					<form  name="frmfilter" id="frmfilter" method="post" action="">
					 <input type="text" name="date_start" id="date_start" autocomplete="off" onkeydown="if(this.value=='Start Date') this.value=''"  value="<?php echo $_REQUEST['date_start']!=""?$_REQUEST['date_start']:'Start Date';?>"> <input type="text" name="date_end" id="date_end" autocomplete="off" onkeydown="if(this.value=='End Date') this.value=''"  value="<?php echo $_REQUEST['date_end']!=""?$_REQUEST['date_end']:'End Date';?>"> <input type="submit" name="filter" id="filter" value="filter">   
					 <script type="text/javascript">
					date_pick('#date_start');
					date_pick('#date_end');
						/*dateFormat:"%d-%m-%Y"*/
						</script>
					</form>
                </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?=$this->actionTitle." [".$this->total_count."]"?></span></h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
						<?if($this->total_count>0){?>
                        <table id="myTable" class="tablesorter">
                   	  <thead>
                                <tr>
				<th style="width:2%">#</th>
					<th style="width:15%">Customer Name</th>
					<th style="width:15%">Email</th>
					<th style="width:15%">Customer Group</th>
					<th style="width:15%">Status</th>
					<th style="width:15%">Reward Points</th>
					<th style="width:15%">No orders</th>
					<th style="width:15%">Total</th>
				</tr>
                            </thead>
                            <tbody>

							<?
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}
							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
				<td class="<?=$class?>"><?php echo $i;?></td>
				<td class="<?=$class?>"><?php echo "<a href='customers?type=Edit&rid=".$result['customer_id']."'>".$result['customer']."</a>";?></td>
				<td class="<?=$class?>"><?php echo $result['customers_email_address'];?></td>
				<td class="<?=$class?>"><?php echo $result['customer_group'];?></td>
				<td class="<?=$class?>"><?php echo $result['customers_status']=='1'?'Enable':'Disable';?></td>
				<td class="<?=$class?>"><?php echo $result['points'];?></td>
				<td class="<?=$class?>"><?php echo $result['orders'];?></td>
				<td class="<?=$class?>"><?php echo $currency->format($result['total']);?></td>

     			     </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table><?}else{
							echo "<table id='myTable' class='tablesorter' border='2'><tr><td align='center'>No records to display</td></tr></table>";
							}?>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                           </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }?>