 
<?php
$act=new Model_Adminaction();
$act_ext=new Model_Adminextaction();
	if($_REQUEST['type']==''){?>
<div class="container_12">
           <div style="clear:both;"></div>
            <div class="grid_12">
  				<?
					if($_REQUEST['msg']!=""){?>
				<span class="notification n-success"><?=base64_decode($_REQUEST['msg']);?></span>
				<?}?>

                <div class="bottom-spacing">
                    <!-- Button -->
                    <div class="float-right"><?=$this->view_pagination;?>
						<?php $act->viewAddB(ADMIN_URL_CONTROLLER.$this->actionTitle);?>
                    </div>
                   </div>


                <!-- Example table -->
                <div class="module">
                	<h2><span><?="Tax Class"." [".$this->total_count."]"?></span></h2>

                    <div class="module-table-body">
                    	<form name="frmMain" id="frmMain" method="post" action="<?php echo ADMIN_URL_CONTROLLER.$this->actionTitle?>">
                      <?if($this->total_count>0){?>
						<table id="myTable" class="tablesorter" border="2">
                   	  <thead>
                                <tr>
				  <th align="center" style="width:5%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#</th>
				  <th align="center" style="width:2%">Tax_Class_Id</th>
                                  <th style="width:20%"><?php echo $act_ext->getSortLable(array("disType"=>$this->disType, "sortby"=>"tax_class_title", "page"=>$_REQUEST['page'] ,"file"=>"taxclass" ,"label"=>"Title"));?></th>
                                  <th style="width:21%">Description</th>
                                  <th style="width:15%"><input type="checkbox" name="checkall" id="checkall" onClick="Checkall()"/> <a href="#">Action</a></th>
                                </tr>
                            </thead>
                            <tbody>

							<?
					$i=1;
					if($this->page!=1)
					{
						$i+=($this->page-1)*$this->per_page;
					}

							foreach ($this->results as $result)
							{

							$class=fmod($i,2)==0?'':'addcolorne';
							?>
                              <tr>
                                <td align="center" class="<?=$class?>"><?=$i?></td>
				<td align="center" class="<?=$class?>"><?=$result['tax_class_id']?></td>
                               <td class="<?=$class?>"><?php echo $result['tax_class_title'];   ?></td>
                                <td class="<?=$class?>"><?php echo $result['tax_class_description'];   ?></td>

                                <td class="<?=$class?>">

								<input type="checkbox" name="rid[]" id="rid" value="<?php echo $result['tax_class_id'];?>"  />
								<?php
									$act->viewEditB(ADMIN_URL_CONTROLLER.$this->actionTitle,$result['tax_class_id'],$_REQUEST['page']);
									$act->viewDelB($this->actionTitle,$result['tax_class_id'],'r_tax_class','tax_class_id',$_REQUEST['page']);
								?>

                                </td>
                              </tr>
                              <?$i=$i+1;}?>

                            </tbody>
                        </table><?}else{
							echo "<table id='myTable' class='tablesorter' border='2'><tr><td align='center'>No records to display</td></tr></table>";
							}?>

						<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
                        <div class="table-apply">
                               <?$act->fnmultipleactdropdown(array('Del'=>'Delete'));?>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div>
                </div>

                <?=$this->view_pagination;?>
			</div>
             <div class="grid_6">
		  </div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
        </div>
		<?php }elseif($_REQUEST['type']=='Add' || 'Edit'){
 	/*foreach ($this->data as $result)
	{} print_r($result);*/?>
		<div class="container_12">
          <div style="clear:both;"></div>
          <div style="clear:both;"></div>
            <div class="grid_12">
                <div class="module">
                     <h2><span><?php echo $_REQUEST['type']." ".$this->actionTitle;?></span></h2>
                     <div id="TabbedPanels1" class="TabbedPanels">
                       <ul class="TabbedPanelsTabGroup">
                         <li class="TabbedPanelsTab" tabindex="0">Details</li>
                         <li class="iconsec">
						 <?php echo $act->editCancelB($this->actionTitle,$_REQUEST['page']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editApplyB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type']);?></li>
                         <li class="iconsec">
						 <?php echo $act->editSaveB(ADMIN_URL_CONTROLLER.$this->actionTitle,(int)$_REQUEST['rid'],$_REQUEST['type'],$_REQUEST['page']);?></li>
                       </ul>
                       <div class="TabbedPanelsContentGroup">
                         <div class="TabbedPanelsContent"> <form name="frmEdit" method="post" enctype="multipart/form-data">
                             <?if($this->msg!=""){ echo '<div><span class="notification n-success">'.base64_decode($this->msg).'</span></div> ';}?>
							 <p><b>All fields indicated with * are mandatory</b></p>

                        <div class="mode-box">
<h3><span>Tax Class Details</span></h3>    
			    <? echo $act->field(array('lable'=>'Tax Class Title','input_title'=>'tax_class_title','desc'=>'enter tax class title                                                                            ','input_type'=>'input_text','val'=>$this->data[0]['tax_class_title'],"req"=>'0'));?>
			
 <? echo $act->field(array('lable'=>' Description','input_title'=>'tax_class_description','desc'=>'enter description                                                                           ','input_type'=>'input_text','val'=>$this->data[0]['tax_class_description'],"req"=>'0'));?>
 </div>
 <div class="mode-box">
<h3><span>Geo Zone Details</span></h3>
<table id="tax-rate" class="list">
          <thead>
            <tr>
              <td class="left">Geo Zone</td>
              <td class="left"><span class="required">*</span> Description</td>
              <td class="left"><span class="required">*</span> Tax Rate</td>
              <td class="left"><span class="required">*</span> Priority</td>
              <td></td>
            </tr>
          </thead>
          <?php $tax_rate_row = 0;?>
          <?php foreach ($this->tax_rates as $tax_rate) {?>
          <tbody id="tax-rate-row<?php echo $tax_rate_row; ?>">
            <tr>
              <td class="left"><select name="tax_rate[<?php echo $tax_rate_row; ?>][geo_zone_id]" id="geo-zone-id<?php echo $tax_rate_row; ?>">
                  <?php foreach ($this->geo_zones as $geo_zone) { ?>
                  <?php  if ($geo_zone['geo_zone_id'] == $tax_rate['tax_zone_id']) { ?>
                  <option value="<?php echo $geo_zone['geo_zone_id']; ?>" selected="selected"><?php echo $geo_zone['geo_zone_name']; ?></option>
                  <?php } else { ?>
                  <option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['geo_zone_name']; ?></option>
                  <?php } ?>
                  <?php } ?>
                </select></td>
              <td class="left"><input type="text" name="tax_rate[<?php echo $tax_rate_row; ?>][description]" value="<?php echo $tax_rate['tax_description']; ?>" /></td>
              <td class="left"><input type="text" name="tax_rate[<?php echo $tax_rate_row; ?>][rate]" value="<?php echo $tax_rate['tax_rate']; ?>" /></td>
              <td class="left"><input type="text" name="tax_rate[<?php echo $tax_rate_row; ?>][priority]" value="<?php echo $tax_rate['tax_priority']; ?>" size="1" /></td>
              <td class="left"><a onclick="$('#tax-rate-row<?php echo $tax_rate_row; ?>').remove();" class="button"><span>Remove</span></a></td>
            </tr>
          </tbody>
          <?php $tax_rate_row++; ?>
          <?php } ?>
          <tfoot>
            <tr>
              <td colspan="4"></td>
              <td class="left"><a onclick="addRate();" class="button"><span>Add Tax Rate</span></a></td>
            </tr>
          </tfoot>
        </table>


		</div>				  </div>

                        </form>
                       </div>
                  </div>
                     <div class="module-body">
                  </div>

                </div>
        		<div style="clear:both;"></div>
            </div>
            <div style="clear:both;"></div>
           <div style="clear:both;"></div>
</div>
		<?php }?>

		<script type="text/javascript"><!--
var tax_rate_row = <?php echo $tax_rate_row; ?>;

function addRate() {
	html  = '<tbody id="tax-rate-row' + tax_rate_row + '">';
	html += '<tr>';
	html += '<td class="left"><select name="tax_rate[' + tax_rate_row + '][geo_zone_id]">';
    <?php foreach ($this->geo_zones as $geo_zone) { ?>
    html += '<option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['geo_zone_name']; ?></option>';
    <?php } ?>
	html += '</select></td>';
	html += '<td class="left"><input type="text" name="tax_rate[' + tax_rate_row + '][description]" value="" /></td>';
	html += '<td class="left"><input type="text" name="tax_rate[' + tax_rate_row + '][rate]" value="" /></td>';
	html += '<td class="left"><input type="text" name="tax_rate[' + tax_rate_row + '][priority]" value="" size="1" /></td>';
	html += '<td class="left"><a onclick="$(\'#tax-rate-row' + tax_rate_row + '\').remove();" class="button"><span>Remove</span></a></td>';
	html += '</tr>';
	html += '</tbody>';
	
	$('#tax-rate > tfoot').before(html);
	
	tax_rate_row++;
}
//--></script> 