<!-- start site main content -->
<section id="mainContent">
	<div class="content_top">
		<div class="row">
			<?if(count($this->pos[top])>0){?>
				<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
			<?}?>
		</div>
	</div>
	<!-- start main content bottom -->
	<div class="content_bottom">
		<div class="col-lg-8 col-md-8">
            <!-- start content bottom left -->
			<div class="content_bottom_left">
				
				<div class="archive_style_1">
					<h2>                  
						<span class="bold_line"><span></span></span>
						<span class="solid_line"></span>
						<span class="title_text">Contact Us</span>
					</h2>	
					<?/*?><div class="row">
						 <div class="col-lg-12 col-md-12 col-sm-12">
							<!-- start contact area -->
						   <div class="contact_area">
							 <?php echo $this->data[store]; ?><br />
							 <?php if ($this->data[telephone]) { ?>
										<b><?php echo $this->trans->_('text_telephone_information_contact'); ?></b><br /><?php echo $this->data[telephone];?>
										<br />
									<?php } ?>
							 
							 <p><?php echo $this->data[address]; ?></p>
							 <div class="contact_bottom">

							   <div class="contact_us wow fadeInRightBig">
							   <h2>Contact Us</h2>
								 <form class="contact_form">
								   <input class="form-control" type="text" placeholder="Name(required)">
								   <input class="form-control" type="email" placeholder="E-mail(required)">
								   <input class="form-control" type="text" placeholder="Subject">
								   <textarea class="form-control" cols="30" rows="10" placeholder="Message(required)"></textarea>
								   <input type="submit" value="Send">
								 </form>
							   </div>
							 </div>
						   </div>
						   <!-- End contact area -->
						 </div>
					   </div><?*/?>
				</div>
				<div class="pagination_area">
					<?php echo $this->pagination; ?>
				</div>
				
				<? if(count($this->pos[left])>0){?>
					<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
				<?}?>
			</div><!--End content_bottom_left-->                 
		</div>
		<!-- start content bottom right -->
		<div class="col-lg-4 col-md-4">
			<div class="content_bottom_right">
				<?if(count($this->pos[right])>0){?>
					<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
				<?}?>
			</div>
		</div>
	</div>  
	<div class="content_middle">
		<?if(count($this->pos[bottom])>0){?>
			<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
		<?}?>
	</div><!-- End main content middle -->
</section><!-- End site main content -->