<style>
#sitemap-list li ul li a {
    display: block;
    text-decoration: none;
    list-style-type: none;
    margin-left:  20px;
    margin-top: -5px;
}

#sitemap-list ul li ul li a {
    display: block;
    text-decoration: none;
    list-style-type: none;
    color: #6e90a6;
    margin-left:  50px;
}
</style>
<!-- start site main content -->
<section id="mainContent">
	<div class="content_top">
		<div class="row">
			<?if(count($this->pos[top])>0){?>
				<?php echo $this->action('top','modules',null,array('mod' =>$this->pos[top]));?>
			<?}?>
		</div>
	</div>
	<!-- start main content bottom -->
	<div class="content_bottom">
		<div class="col-lg-8 col-md-8">
            <!-- start content bottom left -->
			<div class="content_bottom_left">
				
				<div class="archive_style_1">
						<h2>                  
							<span class="bold_line"><span></span></span>
							<span class="solid_line"></span>
							<span class="title_text">Site Map</span>
						</h2>	
						
						<div class="single_archive wow fadeInDown">
							<!--<div class="archive_imgcontainer">-->
								<ul id="sitemap-list">
								<?php foreach ($this->data[categories] as $category_1) { ?>
									<li><a href="<?php echo $category_1['href']; ?>"><?php echo $category_1['name']; ?></a>
										<?php if ($category_1['children']) { ?>
											<ul>
												<?php foreach ($category_1['children'] as $category_2) { ?>
													<li><a href="<?php echo $category_2['href']; ?>"><?php echo $category_2['name']; ?></a>
														<?php if ($category_2['children']) { ?>
															<ul>
																<?php foreach ($category_2['children'] as $category_3) { ?>
																	<li><a href="<?php echo $category_3['href']; ?>"><?php echo $category_3['name']; ?></a></li>
																<?php } ?>
															</ul>
														<?php } ?>
													</li>
												<?php } ?>
											</ul>
										<?php } ?>
									</li>
								<?php } ?>
								<li><?php echo $this->trans->_('text_information_information_sitemap'); ?>
									<ul>
										<?php foreach ($this->data[informations] as $information) { ?>
											<li><a href="<?php echo $information['href']; ?>"><?php echo $information['title']; ?></a></li>
										<?php } ?>
										<li><a href="<?php echo $this->url_to_site."information/contact"; ?>"><?php echo $this->trans->_('text_contact_information_sitemap'); ?></a></li>
									</ul>
								</li>
								</ul>
							<!--</div>-->
						</div>
					</div>
					<? if(count($this->pos[left])>0){?>
						<?php echo $this->action('left','modules',null,array('mod' =>$this->pos[left]));?>
					<?}?>
				</div><!--End content_bottom_left-->                 
			</div>
			<!-- start content bottom right -->
			<div class="col-lg-4 col-md-4">
				<div class="content_bottom_right">
					<?if(count($this->pos[right])>0){?>
						<?php echo $this->action('right','modules',null,array('mod' =>$this->pos[right]));?>
					<?}?>
					
				</div>
			</div>
		</div>  
		<div class="content_middle">
			<?if(count($this->pos[bottom])>0){?>
				<?php echo $this->action('bottom','modules',null,array('mod' =>$this->pos[bottom]));?>
			<?}?>
		</div><!-- End main content middle -->
	</section><!-- End site main content -->	